#=========================================================================
# Example Macro LEF and GDS import
#=========================================================================

name: example-macro

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - user_proj_example.lef
  - user_proj_example.gds.gz
 
#-------------------------------------------------------------------------
# Commands
#------------------------------------------------------------------------- 
  
commands:
  - cp ../../../lef/user_proj_example.lef outputs/user_proj_example.lef
  - cp ../../../gds/user_proj_example.gds.gz outputs/user_proj_example.gds.gz