#=========================================================================
# Constraints
#=========================================================================

name: design-constraints

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - constraints.tcl

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  clock_period: 10.0
  design_name: undefined

