#=========================================================================
# Design testebench node
#=========================================================================

name: design-testbench

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:

#-------------------------------------------------------------------------
# Commands
#------------------------------------------------------------------------- 
  
commands:
