#=========================================================================
# Innovus node for the initial floorplan of the userproject wrapper
#=========================================================================

name: caravel-uprj-floorplan

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  # DEF file for caravel user project wrapper projcts
  - user_project_wrapper.def
  # The initial floorplan for the MWP is given as a def file
  # and must given in the foundation flow setup
  # the setup.tcl can be extened by an additional setup.tcl at the input 
  # of the cadence-innovus-flowsetup step
  - setup.tcl

#-------------------------------------------------------------------------
# Commands
#------------------------------------------------------------------------- 
commands:
  # this script removes all power stripes and cell-pg connections,
  # since this is handled by innovus
  # it requires an input floorplan def file from the last
  # generated def file of the floorplan stage of openlane
  - python3 ./generate_init_def.py
  # a result of the script can be found in this directory

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  # overwrite script order parameter of innovus init step 
  # remove floorplanning and pin assignment for now
  iInit_order:
    - main.tcl
    - quality-of-life.tcl
    - add-endcaps-welltaps.tcl
    - make-path-groups.tcl
    - reporting.tcl
