/*
###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID localhost.localdomain)
#  Generated on:      Thu Jun 17 18:21:47 2021
#  Design:            user_proj_example
###############################################################
*/
module user_proj_example_SNPS_CLOCK_GATE_HIGH_counter_BITS32_0 (
	EN, 
	TE, 
	ENCLK, 
	ENCLK_clone1, 
	ENCLK_clone2, 
	CLK, 
	vccd1, 
	vssd1);
   input EN;
   input TE;
   output ENCLK;
   output ENCLK_clone1;
   output ENCLK_clone2;
   input CLK;
   inout vccd1;
   inout vssd1;

   // Module instantiations
   sky130_fd_sc_hd__sdlclkp_4 latch_clone_5 (
	.CLK(CLK),
	.GATE(EN),
	.GCLK(ENCLK_clone2),
	.SCE(TE), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__sdlclkp_4 latch_clone_4 (
	.CLK(CLK),
	.GATE(EN),
	.GCLK(ENCLK_clone1),
	.SCE(TE), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__sdlclkp_4 latch_clone (
	.CLK(CLK),
	.GATE(EN),
	.GCLK(ENCLK),
	.SCE(TE), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
endmodule

module user_proj_example_SNPS_CLOCK_GATE_HIGH_counter_BITS32_4 (
	CLK, 
	EN, 
	ENCLK, 
	TE, 
	vccd1, 
	vssd1);
   input CLK;
   input EN;
   output ENCLK;
   input TE;
   inout vccd1;
   inout vssd1;

   // Module instantiations
   sky130_fd_sc_hd__sdlclkp_4 latch (
	.CLK(CLK),
	.GATE(EN),
	.GCLK(ENCLK),
	.SCE(TE), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
endmodule

module user_proj_example_SNPS_CLOCK_GATE_HIGH_counter_BITS32_3 (
	CLK, 
	EN, 
	ENCLK, 
	TE, 
	vccd1, 
	vssd1);
   input CLK;
   input EN;
   output ENCLK;
   input TE;
   inout vccd1;
   inout vssd1;

   // Module instantiations
   sky130_fd_sc_hd__sdlclkp_4 latch (
	.CLK(CLK),
	.GATE(EN),
	.GCLK(ENCLK),
	.SCE(TE), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
endmodule

module user_proj_example_SNPS_CLOCK_GATE_HIGH_counter_BITS32_2 (
	CLK, 
	EN, 
	ENCLK, 
	TE, 
	vccd1, 
	vssd1);
   input CLK;
   input EN;
   output ENCLK;
   input TE;
   inout vccd1;
   inout vssd1;

   // Module instantiations
   sky130_fd_sc_hd__sdlclkp_4 latch (
	.CLK(CLK),
	.GATE(EN),
	.GCLK(ENCLK),
	.SCE(TE), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
endmodule

module user_proj_example_SNPS_CLOCK_GATE_HIGH_counter_BITS32_1 (
	CLK, 
	EN, 
	ENCLK, 
	TE, 
	vccd1, 
	vssd1);
   input CLK;
   input EN;
   output ENCLK;
   input TE;
   inout vccd1;
   inout vssd1;

   // Module instantiations
   sky130_fd_sc_hd__sdlclkp_4 latch (
	.CLK(CLK),
	.GATE(EN),
	.GCLK(ENCLK),
	.SCE(TE), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
endmodule

module user_proj_example_counter_BITS32_DW01_inc_J1_0_0 (
	A, 
	SUM, 
	vccd1, 
	vssd1);
   input [31:0] A;
   output [31:0] SUM;
   inout vccd1;
   inout vssd1;

   // Internal wires
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n111;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;

   // Module instantiations
   sky130_fd_sc_hd__ha_2 U35 (
	.A(A[28]),
	.B(n126),
	.COUT(n127),
	.SUM(SUM[28]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U36 (
	.A(A[23]),
	.B(n121),
	.COUT(n122),
	.SUM(SUM[23]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U37 (
	.A(A[18]),
	.B(n116),
	.COUT(n117),
	.SUM(SUM[18]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U38 (
	.A(A[14]),
	.B(n112),
	.COUT(n113),
	.SUM(SUM[14]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U39 (
	.A(A[10]),
	.B(n108),
	.COUT(n109),
	.SUM(SUM[10]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U40 (
	.A(A[6]),
	.B(n104),
	.COUT(n105),
	.SUM(SUM[6]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U41 (
	.A(A[2]),
	.B(n100),
	.COUT(n101),
	.SUM(SUM[2]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U42 (
	.A(A[0]),
	.Y(SUM[0]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__xor2_1 U43 (
	.A(n99),
	.B(A[31]),
	.X(SUM[31]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U44 (
	.A(A[1]),
	.B(A[0]),
	.COUT(n100),
	.SUM(SUM[1]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U45 (
	.A(A[3]),
	.B(n101),
	.COUT(n102),
	.SUM(SUM[3]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U46 (
	.A(A[4]),
	.B(n102),
	.COUT(n103),
	.SUM(SUM[4]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U47 (
	.A(A[5]),
	.B(n103),
	.COUT(n104),
	.SUM(SUM[5]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U48 (
	.A(A[7]),
	.B(n105),
	.COUT(n106),
	.SUM(SUM[7]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U49 (
	.A(A[8]),
	.B(n106),
	.COUT(n107),
	.SUM(SUM[8]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U50 (
	.A(A[9]),
	.B(n107),
	.COUT(n108),
	.SUM(SUM[9]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U51 (
	.A(A[11]),
	.B(n109),
	.COUT(n110),
	.SUM(SUM[11]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U52 (
	.A(A[12]),
	.B(n110),
	.COUT(n111),
	.SUM(SUM[12]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U53 (
	.A(A[13]),
	.B(n111),
	.COUT(n112),
	.SUM(SUM[13]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U54 (
	.A(A[15]),
	.B(n113),
	.COUT(n114),
	.SUM(SUM[15]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U55 (
	.A(A[16]),
	.B(n114),
	.COUT(n115),
	.SUM(SUM[16]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U56 (
	.A(A[17]),
	.B(n115),
	.COUT(n116),
	.SUM(SUM[17]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U57 (
	.A(A[19]),
	.B(n117),
	.COUT(n118),
	.SUM(SUM[19]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U58 (
	.A(A[20]),
	.B(n118),
	.COUT(n119),
	.SUM(SUM[20]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U59 (
	.A(A[21]),
	.B(n119),
	.COUT(n120),
	.SUM(SUM[21]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U60 (
	.A(A[22]),
	.B(n120),
	.COUT(n121),
	.SUM(SUM[22]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U61 (
	.A(A[24]),
	.B(n122),
	.COUT(n123),
	.SUM(SUM[24]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U62 (
	.A(A[25]),
	.B(n123),
	.COUT(n124),
	.SUM(SUM[25]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U63 (
	.A(A[26]),
	.B(n124),
	.COUT(n125),
	.SUM(SUM[26]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U64 (
	.A(A[27]),
	.B(n125),
	.COUT(n126),
	.SUM(SUM[27]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U65 (
	.A(A[29]),
	.B(n127),
	.COUT(n128),
	.SUM(SUM[29]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U66 (
	.A(A[30]),
	.B(n128),
	.COUT(n99),
	.SUM(SUM[30]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
endmodule

module user_proj_example_counter_BITS32_0 (
	clk, 
	reset, 
	valid, 
	wstrb, 
	wdata, 
	la_write, 
	la_input, 
	ready, 
	rdata, 
	count, 
	vccd1, 
	vssd1);
   input clk;
   input reset;
   input valid;
   input [3:0] wstrb;
   input [31:0] wdata;
   input [31:0] la_write;
   input [31:0] la_input;
   output ready;
   output [31:0] rdata;
   output [31:0] count;
   inout vccd1;
   inout vssd1;

   // Internal wires
   wire CTS_21;
   wire CTS_20;
   wire CTS_19;
   wire CTS_18;
   wire CTS_17;
   wire CTS_3;
   wire CTS_2;
   wire n_Logic0_;
   wire N11;
   wire N12;
   wire N13;
   wire N14;
   wire N15;
   wire N16;
   wire N17;
   wire N18;
   wire N19;
   wire N20;
   wire N21;
   wire N22;
   wire N23;
   wire N24;
   wire N25;
   wire N26;
   wire N27;
   wire N28;
   wire N29;
   wire N30;
   wire N31;
   wire N32;
   wire N33;
   wire N34;
   wire N35;
   wire N36;
   wire N37;
   wire N38;
   wire N39;
   wire N40;
   wire N41;
   wire N42;
   wire N120;
   wire N123;
   wire N124;
   wire N125;
   wire N126;
   wire N127;
   wire N128;
   wire N129;
   wire N130;
   wire N132;
   wire N133;
   wire N134;
   wire N135;
   wire N136;
   wire N137;
   wire N138;
   wire N139;
   wire N141;
   wire N142;
   wire N143;
   wire N144;
   wire N145;
   wire N146;
   wire N147;
   wire N148;
   wire N150;
   wire N151;
   wire N152;
   wire N153;
   wire N154;
   wire N155;
   wire N156;
   wire N157;
   wire N158;
   wire net475;
   wire net478;
   wire net481;
   wire net484;
   wire net487;
   wire net490;
   wire net493;
   wire net496;
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n1100;
   wire n1210;
   wire n131;
   wire n140;
   wire n159;
   wire n160;
   wire n170;
   wire n180;
   wire n190;
   wire n200;
   wire n210;
   wire n220;
   wire n230;
   wire n240;
   wire n250;
   wire n260;
   wire n270;
   wire n280;
   wire n290;
   wire n300;
   wire n310;
   wire n320;
   wire n330;
   wire n340;
   wire n350;
   wire n360;
   wire n370;
   wire n380;
   wire n390;
   wire n400;
   wire n410;
   wire n420;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n1101;
   wire n111;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n1200;
   wire n1211;
   wire n122;
   wire n1230;

   // Module instantiations
   sky130_fd_sc_hd__diode_2 DIODE_9 (
	.DIODE(la_input[21]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__diode_2 DIODE_8 (
	.DIODE(la_input[22]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__diode_2 DIODE_7 (
	.DIODE(wdata[2]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__diode_2 DIODE_6 (
	.DIODE(wdata[7]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__diode_2 DIODE_5 (
	.DIODE(wdata[6]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__diode_2 DIODE_4 (
	.DIODE(la_input[19]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__diode_2 DIODE_3 (
	.DIODE(wdata[11]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__diode_2 DIODE_2 (
	.DIODE(wdata[16]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__diode_2 DIODE_1 (
	.DIODE(la_input[9]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_2 CTS_ccl_a_INV_ideal_wb_clock_G0_L3_2 (
	.A(CTS_21),
	.Y(CTS_20), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_2 CTS_ccl_a_INV_ideal_wb_clock_G0_L2_1 (
	.A(clk),
	.Y(CTS_21), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_4 CTS_csf_INV_ideal_wb_clock_G1_L4_1 (
	.A(CTS_18),
	.Y(CTS_17), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_2 CTS_csf_INV_ideal_wb_clock_G1_L3_1 (
	.A(CTS_19),
	.Y(CTS_18), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   user_proj_example_SNPS_CLOCK_GATE_HIGH_counter_BITS32_0 clk_gate_rdata_reg (
	.EN(N158),
	.TE(n_Logic0_),
	.ENCLK(CTS_19),
	.ENCLK_clone1(CTS_2),
	.ENCLK_clone2(CTS_3),
	.CLK(clk), 
	.vccd1(vccd1), 
	.vssd1(vssd1));
   user_proj_example_SNPS_CLOCK_GATE_HIGH_counter_BITS32_4 clk_gate_count_reg (
	.CLK(clk),
	.EN(net475),
	.ENCLK(net478),
	.TE(n_Logic0_), 
	.vccd1(vccd1), 
	.vssd1(vssd1));
   user_proj_example_SNPS_CLOCK_GATE_HIGH_counter_BITS32_3 clk_gate_count_reg_0 (
	.CLK(clk),
	.EN(net481),
	.ENCLK(net484),
	.TE(n_Logic0_), 
	.vccd1(vccd1), 
	.vssd1(vssd1));
   user_proj_example_SNPS_CLOCK_GATE_HIGH_counter_BITS32_2 clk_gate_count_reg_1 (
	.CLK(clk),
	.EN(net487),
	.ENCLK(net490),
	.TE(n_Logic0_), 
	.vccd1(vccd1), 
	.vssd1(vssd1));
   user_proj_example_SNPS_CLOCK_GATE_HIGH_counter_BITS32_1 clk_gate_count_reg_2 (
	.CLK(clk),
	.EN(net493),
	.ENCLK(net496),
	.TE(n_Logic0_), 
	.vccd1(vccd1), 
	.vssd1(vssd1));
   user_proj_example_counter_BITS32_DW01_inc_J1_0_0 add_x_1 (
	.A(count),
	.SUM({ N42,
		N41,
		N40,
		N39,
		N38,
		N37,
		N36,
		N35,
		N34,
		N33,
		N32,
		N31,
		N30,
		N29,
		N28,
		N27,
		N26,
		N25,
		N24,
		N23,
		N22,
		N21,
		N20,
		N19,
		N18,
		N17,
		N16,
		N15,
		N14,
		N13,
		N12,
		N11 }), 
	.vccd1(vccd1), 
	.vssd1(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_0_ (
	.CLK(CTS_3),
	.D(count[0]),
	.Q(rdata[0]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_1_ (
	.CLK(CTS_3),
	.D(count[1]),
	.Q(rdata[1]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_2_ (
	.CLK(CTS_3),
	.D(count[2]),
	.Q(rdata[2]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_3_ (
	.CLK(CTS_3),
	.D(count[3]),
	.Q(rdata[3]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_4_ (
	.CLK(CTS_3),
	.D(count[4]),
	.Q(rdata[4]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_5_ (
	.CLK(CTS_3),
	.D(count[5]),
	.Q(rdata[5]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_6_ (
	.CLK(CTS_3),
	.D(count[6]),
	.Q(rdata[6]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_7_ (
	.CLK(CTS_3),
	.D(count[7]),
	.Q(rdata[7]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_8_ (
	.CLK(CTS_3),
	.D(count[8]),
	.Q(rdata[8]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_9_ (
	.CLK(CTS_17),
	.D(count[9]),
	.Q(rdata[9]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_10_ (
	.CLK(CTS_17),
	.D(count[10]),
	.Q(rdata[10]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_11_ (
	.CLK(CTS_17),
	.D(count[11]),
	.Q(rdata[11]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_12_ (
	.CLK(CTS_17),
	.D(count[12]),
	.Q(rdata[12]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_13_ (
	.CLK(CTS_17),
	.D(count[13]),
	.Q(rdata[13]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_14_ (
	.CLK(CTS_3),
	.D(count[14]),
	.Q(rdata[14]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_15_ (
	.CLK(CTS_17),
	.D(count[15]),
	.Q(rdata[15]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_16_ (
	.CLK(CTS_17),
	.D(count[16]),
	.Q(rdata[16]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_17_ (
	.CLK(CTS_17),
	.D(count[17]),
	.Q(rdata[17]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_18_ (
	.CLK(CTS_17),
	.D(count[18]),
	.Q(rdata[18]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_19_ (
	.CLK(CTS_17),
	.D(count[19]),
	.Q(rdata[19]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_20_ (
	.CLK(CTS_17),
	.D(count[20]),
	.Q(rdata[20]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_21_ (
	.CLK(CTS_2),
	.D(count[21]),
	.Q(rdata[21]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_22_ (
	.CLK(CTS_2),
	.D(count[22]),
	.Q(rdata[22]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_23_ (
	.CLK(CTS_17),
	.D(count[23]),
	.Q(rdata[23]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_24_ (
	.CLK(CTS_2),
	.D(count[24]),
	.Q(rdata[24]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_25_ (
	.CLK(CTS_2),
	.D(count[25]),
	.Q(rdata[25]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_26_ (
	.CLK(CTS_2),
	.D(count[26]),
	.Q(rdata[26]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_27_ (
	.CLK(CTS_2),
	.D(count[27]),
	.Q(rdata[27]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_28_ (
	.CLK(CTS_2),
	.D(count[28]),
	.Q(rdata[28]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_29_ (
	.CLK(CTS_2),
	.D(count[29]),
	.Q(rdata[29]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_30_ (
	.CLK(CTS_2),
	.D(count[30]),
	.Q(rdata[30]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_31_ (
	.CLK(CTS_2),
	.D(count[31]),
	.Q(rdata[31]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_26_ (
	.CLK(net478),
	.D(n6),
	.Q(count[26]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_27_ (
	.CLK(net478),
	.D(n5),
	.Q(count[27]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_28_ (
	.CLK(net478),
	.D(n4),
	.Q(count[28]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_29_ (
	.CLK(net478),
	.D(n3),
	.Q(count[29]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_30_ (
	.CLK(net478),
	.D(n2),
	.Q(count[30]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_31_ (
	.CLK(net478),
	.D(n1),
	.Q(count[31]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 ready_reg (
	.CLK(CTS_20),
	.D(n330),
	.Q(ready), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_20_ (
	.CLK(net484),
	.D(n1210),
	.Q(count[20]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_21_ (
	.CLK(net484),
	.D(n1100),
	.Q(count[21]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_22_ (
	.CLK(net484),
	.D(n10),
	.Q(count[22]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_23_ (
	.CLK(net484),
	.D(n9),
	.Q(count[23]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_24_ (
	.CLK(net478),
	.D(n8),
	.Q(count[24]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_25_ (
	.CLK(net478),
	.D(n7),
	.Q(count[25]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_14_ (
	.CLK(net490),
	.D(n180),
	.Q(count[14]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_15_ (
	.CLK(net490),
	.D(n170),
	.Q(count[15]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_16_ (
	.CLK(net484),
	.D(n160),
	.Q(count[16]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_17_ (
	.CLK(net484),
	.D(n159),
	.Q(count[17]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_18_ (
	.CLK(net484),
	.D(n140),
	.Q(count[18]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_19_ (
	.CLK(net484),
	.D(n131),
	.Q(count[19]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_8_ (
	.CLK(net490),
	.D(n240),
	.Q(count[8]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_9_ (
	.CLK(net490),
	.D(n230),
	.Q(count[9]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_10_ (
	.CLK(net490),
	.D(n220),
	.Q(count[10]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_11_ (
	.CLK(net490),
	.D(n210),
	.Q(count[11]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_12_ (
	.CLK(net490),
	.D(n200),
	.Q(count[12]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_13_ (
	.CLK(net490),
	.D(n190),
	.Q(count[13]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_3_ (
	.CLK(net496),
	.D(n290),
	.Q(count[3]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_4_ (
	.CLK(net496),
	.D(n280),
	.Q(count[4]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_5_ (
	.CLK(net496),
	.D(n270),
	.Q(count[5]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_6_ (
	.CLK(net496),
	.D(n260),
	.Q(count[6]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_7_ (
	.CLK(net496),
	.D(n250),
	.Q(count[7]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_1_ (
	.CLK(net496),
	.D(n310),
	.Q(count[1]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_2_ (
	.CLK(net496),
	.D(n300),
	.Q(count[2]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_0_ (
	.CLK(net496),
	.D(n320),
	.Q(count[0]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U3 (
	.A(reset),
	.B_N(N157),
	.Y(n1), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U4 (
	.A(reset),
	.B_N(N156),
	.Y(n2), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U5 (
	.A(reset),
	.B_N(N155),
	.Y(n3), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U34 (
	.A(reset),
	.B_N(N123),
	.Y(n320), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U18 (
	.A(reset),
	.B_N(N141),
	.Y(n160), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U26 (
	.A(reset),
	.B_N(N132),
	.Y(n240), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U10 (
	.A(reset),
	.B_N(N150),
	.Y(n8), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U17 (
	.A(reset),
	.B_N(N142),
	.Y(n159), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U16 (
	.A(reset),
	.B_N(N143),
	.Y(n140), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U28 (
	.A(reset),
	.B_N(N129),
	.Y(n260), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U15 (
	.A(reset),
	.B_N(N144),
	.Y(n131), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U30 (
	.A(reset),
	.B_N(N127),
	.Y(n280), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U31 (
	.A(reset),
	.B_N(N126),
	.Y(n290), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U29 (
	.A(reset),
	.B_N(N128),
	.Y(n270), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U32 (
	.A(reset),
	.B_N(N125),
	.Y(n300), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U33 (
	.A(reset),
	.B_N(N124),
	.Y(n310), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U21 (
	.A(reset),
	.B_N(N137),
	.Y(n190), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U25 (
	.A(reset),
	.B_N(N133),
	.Y(n230), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U7 (
	.A(reset),
	.B_N(N153),
	.Y(n5), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U8 (
	.A(reset),
	.B_N(N152),
	.Y(n6), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U12 (
	.A(reset),
	.B_N(N147),
	.Y(n10), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U13 (
	.A(reset),
	.B_N(N146),
	.Y(n1100), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U14 (
	.A(reset),
	.B_N(N145),
	.Y(n1210), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U19 (
	.A(reset),
	.B_N(N139),
	.Y(n170), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U20 (
	.A(reset),
	.B_N(N138),
	.Y(n180), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U9 (
	.A(reset),
	.B_N(N151),
	.Y(n7), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U27 (
	.A(reset),
	.B_N(N130),
	.Y(n250), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U11 (
	.A(reset),
	.B_N(N148),
	.Y(n9), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U24 (
	.A(reset),
	.B_N(N134),
	.Y(n220), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U22 (
	.A(reset),
	.B_N(N136),
	.Y(n200), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U23 (
	.A(reset),
	.B_N(N135),
	.Y(n210), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U6 (
	.A(reset),
	.B_N(N154),
	.Y(n4), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U35 (
	.A(reset),
	.B_N(N120),
	.Y(n330), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U36 (
	.A(n103),
	.Y(n119), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U37 (
	.A(n65),
	.Y(n81), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_4 U38 (
	.A(N120),
	.B(n45),
	.Y(n1200), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U39 (
	.A(n1230),
	.Y(N120), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U40 (
	.A(n46),
	.Y(n62), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U41 (
	.A(n84),
	.Y(n100), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__conb_1 U42 (
	.LO(n_Logic0_), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2b_1 U43 (
	.A_N(ready),
	.B(valid),
	.Y(n1230), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor4_1 U44 (
	.A(la_write[11]),
	.B(la_write[10]),
	.C(la_write[9]),
	.D(la_write[8]),
	.Y(n370), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor4_1 U45 (
	.A(la_write[15]),
	.B(la_write[14]),
	.C(la_write[13]),
	.D(la_write[12]),
	.Y(n360), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor4_1 U46 (
	.A(la_write[3]),
	.B(la_write[2]),
	.C(la_write[1]),
	.D(la_write[0]),
	.Y(n350), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor4_1 U47 (
	.A(la_write[7]),
	.B(la_write[6]),
	.C(la_write[5]),
	.D(la_write[4]),
	.Y(n340), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand4_1 U48 (
	.A(n370),
	.B(n360),
	.C(n350),
	.D(n340),
	.Y(n43), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor4_1 U49 (
	.A(la_write[27]),
	.B(la_write[26]),
	.C(la_write[25]),
	.D(la_write[24]),
	.Y(n410), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor4_1 U50 (
	.A(la_write[31]),
	.B(la_write[30]),
	.C(la_write[29]),
	.D(la_write[28]),
	.Y(n400), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor4_1 U51 (
	.A(la_write[19]),
	.B(la_write[18]),
	.C(la_write[17]),
	.D(la_write[16]),
	.Y(n390), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor4_1 U52 (
	.A(la_write[23]),
	.B(la_write[22]),
	.C(la_write[21]),
	.D(la_write[20]),
	.Y(n380), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand4_1 U53 (
	.A(n410),
	.B(n400),
	.C(n390),
	.D(n380),
	.Y(n420), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U54 (
	.A(n43),
	.B(n420),
	.Y(n45), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor3_1 U55 (
	.A(n45),
	.B(reset),
	.C(n1230),
	.Y(n44), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U56 (
	.A(N120),
	.B(wstrb[3]),
	.Y(n103), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U57 (
	.A(n44),
	.B(n103),
	.Y(net475), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U58 (
	.A(N120),
	.B(wstrb[2]),
	.Y(n84), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U59 (
	.A(n44),
	.B(n84),
	.Y(net481), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U60 (
	.A(N120),
	.B(wstrb[1]),
	.Y(n65), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U61 (
	.A(n44),
	.B(n65),
	.Y(net487), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U62 (
	.A(N120),
	.B(wstrb[0]),
	.Y(n46), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U63 (
	.A(n44),
	.B(n46),
	.Y(net493), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U64 (
	.A(la_write[0]),
	.B(la_input[0]),
	.C(n1200),
	.Y(n48), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U65 (
	.A(n1200),
	.B(n62),
	.Y(n61), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U66 (
	.A1(n62),
	.A2(wdata[0]),
	.B1(n61),
	.B2(N11),
	.Y(n47), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U67 (
	.A(n48),
	.B(n47),
	.Y(N123), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U68 (
	.A1(n62),
	.A2(wdata[1]),
	.B1(n61),
	.B2(N12),
	.Y(n50), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U69 (
	.A(la_write[1]),
	.B(n1200),
	.C(la_input[1]),
	.Y(n49), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U70 (
	.A(n50),
	.B(n49),
	.Y(N124), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U71 (
	.A1(n62),
	.A2(wdata[2]),
	.B1(n61),
	.B2(N13),
	.Y(n52), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U72 (
	.A(la_write[2]),
	.B(n1200),
	.C(la_input[2]),
	.Y(n51), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U73 (
	.A(n52),
	.B(n51),
	.Y(N125), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U74 (
	.A1(n62),
	.A2(wdata[3]),
	.B1(n61),
	.B2(N14),
	.Y(n54), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U75 (
	.A(la_write[3]),
	.B(n1200),
	.C(la_input[3]),
	.Y(n53), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U76 (
	.A(n54),
	.B(n53),
	.Y(N126), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U77 (
	.A1(n62),
	.A2(wdata[4]),
	.B1(n61),
	.B2(N15),
	.Y(n56), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U78 (
	.A(la_write[4]),
	.B(n1200),
	.C(la_input[4]),
	.Y(n55), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U79 (
	.A(n56),
	.B(n55),
	.Y(N127), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U80 (
	.A1(n62),
	.A2(wdata[5]),
	.B1(n61),
	.B2(N16),
	.Y(n58), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U81 (
	.A(la_write[5]),
	.B(n1200),
	.C(la_input[5]),
	.Y(n57), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U82 (
	.A(n58),
	.B(n57),
	.Y(N128), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U83 (
	.A1(n62),
	.A2(wdata[6]),
	.B1(n61),
	.B2(N17),
	.Y(n60), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U84 (
	.A(la_write[6]),
	.B(n1200),
	.C(la_input[6]),
	.Y(n59), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U85 (
	.A(n60),
	.B(n59),
	.Y(N129), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U86 (
	.A1(n62),
	.A2(wdata[7]),
	.B1(n61),
	.B2(N18),
	.Y(n64), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U87 (
	.A(la_write[7]),
	.B(n1200),
	.C(la_input[7]),
	.Y(n63), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U88 (
	.A(n64),
	.B(n63),
	.Y(N130), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U89 (
	.A(la_write[8]),
	.B(la_input[8]),
	.C(n1200),
	.Y(n67), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U90 (
	.A(n1200),
	.B(n81),
	.Y(n80), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U91 (
	.A1(n81),
	.A2(wdata[8]),
	.B1(n80),
	.B2(N19),
	.Y(n66), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U92 (
	.A(n67),
	.B(n66),
	.Y(N132), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U93 (
	.A1(n81),
	.A2(wdata[9]),
	.B1(n80),
	.B2(N20),
	.Y(n69), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U94 (
	.A(la_write[9]),
	.B(n1200),
	.C(la_input[9]),
	.Y(n68), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U95 (
	.A(n69),
	.B(n68),
	.Y(N133), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U96 (
	.A1(n81),
	.A2(wdata[10]),
	.B1(n80),
	.B2(N21),
	.Y(n71), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U97 (
	.A(la_write[10]),
	.B(n1200),
	.C(la_input[10]),
	.Y(n70), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U98 (
	.A(n71),
	.B(n70),
	.Y(N134), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U99 (
	.A1(n81),
	.A2(wdata[11]),
	.B1(n80),
	.B2(N22),
	.Y(n73), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U100 (
	.A(la_write[11]),
	.B(n1200),
	.C(la_input[11]),
	.Y(n72), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U101 (
	.A(n73),
	.B(n72),
	.Y(N135), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U102 (
	.A1(n81),
	.A2(wdata[12]),
	.B1(n80),
	.B2(N23),
	.Y(n75), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U103 (
	.A(la_write[12]),
	.B(n1200),
	.C(la_input[12]),
	.Y(n74), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U104 (
	.A(n75),
	.B(n74),
	.Y(N136), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U105 (
	.A1(n81),
	.A2(wdata[13]),
	.B1(n80),
	.B2(N24),
	.Y(n77), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U106 (
	.A(la_write[13]),
	.B(n1200),
	.C(la_input[13]),
	.Y(n76), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U107 (
	.A(n77),
	.B(n76),
	.Y(N137), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U108 (
	.A1(n81),
	.A2(wdata[14]),
	.B1(n80),
	.B2(N25),
	.Y(n79), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U109 (
	.A(la_write[14]),
	.B(n1200),
	.C(la_input[14]),
	.Y(n78), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U110 (
	.A(n79),
	.B(n78),
	.Y(N138), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U111 (
	.A1(n81),
	.A2(wdata[15]),
	.B1(n80),
	.B2(N26),
	.Y(n83), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U112 (
	.A(la_write[15]),
	.B(n1200),
	.C(la_input[15]),
	.Y(n82), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U113 (
	.A(n83),
	.B(n82),
	.Y(N139), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U114 (
	.A(la_write[16]),
	.B(la_input[16]),
	.C(n1200),
	.Y(n86), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U115 (
	.A(n1200),
	.B(n100),
	.Y(n99), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U116 (
	.A1(n100),
	.A2(wdata[16]),
	.B1(n99),
	.B2(N27),
	.Y(n85), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U117 (
	.A(n86),
	.B(n85),
	.Y(N141), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U118 (
	.A1(n100),
	.A2(wdata[17]),
	.B1(n99),
	.B2(N28),
	.Y(n88), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U119 (
	.A(la_write[17]),
	.B(n1200),
	.C(la_input[17]),
	.Y(n87), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U120 (
	.A(n88),
	.B(n87),
	.Y(N142), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U121 (
	.A1(n100),
	.A2(wdata[18]),
	.B1(n99),
	.B2(N29),
	.Y(n90), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U122 (
	.A(la_write[18]),
	.B(n1200),
	.C(la_input[18]),
	.Y(n89), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U123 (
	.A(n90),
	.B(n89),
	.Y(N143), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U124 (
	.A1(n100),
	.A2(wdata[19]),
	.B1(n99),
	.B2(N30),
	.Y(n92), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U125 (
	.A(la_write[19]),
	.B(n1200),
	.C(la_input[19]),
	.Y(n91), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U126 (
	.A(n92),
	.B(n91),
	.Y(N144), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U127 (
	.A1(n100),
	.A2(wdata[20]),
	.B1(n99),
	.B2(N31),
	.Y(n94), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U128 (
	.A(la_write[20]),
	.B(n1200),
	.C(la_input[20]),
	.Y(n93), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U129 (
	.A(n94),
	.B(n93),
	.Y(N145), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U130 (
	.A1(n100),
	.A2(wdata[21]),
	.B1(n99),
	.B2(N32),
	.Y(n96), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U131 (
	.A(la_write[21]),
	.B(n1200),
	.C(la_input[21]),
	.Y(n95), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U132 (
	.A(n96),
	.B(n95),
	.Y(N146), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U133 (
	.A1(n100),
	.A2(wdata[22]),
	.B1(n99),
	.B2(N33),
	.Y(n98), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U134 (
	.A(la_write[22]),
	.B(n1200),
	.C(la_input[22]),
	.Y(n97), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U135 (
	.A(n98),
	.B(n97),
	.Y(N147), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U136 (
	.A1(n100),
	.A2(wdata[23]),
	.B1(n99),
	.B2(N34),
	.Y(n102), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U137 (
	.A(la_write[23]),
	.B(n1200),
	.C(la_input[23]),
	.Y(n101), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U138 (
	.A(n102),
	.B(n101),
	.Y(N148), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U139 (
	.A(la_write[24]),
	.B(la_input[24]),
	.C(n1200),
	.Y(n105), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U140 (
	.A(n1200),
	.B(n119),
	.Y(n118), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U141 (
	.A1(n119),
	.A2(wdata[24]),
	.B1(n118),
	.B2(N35),
	.Y(n104), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U142 (
	.A(n105),
	.B(n104),
	.Y(N150), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U143 (
	.A1(n119),
	.A2(wdata[25]),
	.B1(n118),
	.B2(N36),
	.Y(n107), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U144 (
	.A(la_write[25]),
	.B(n1200),
	.C(la_input[25]),
	.Y(n106), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U145 (
	.A(n107),
	.B(n106),
	.Y(N151), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U146 (
	.A1(n119),
	.A2(wdata[26]),
	.B1(n118),
	.B2(N37),
	.Y(n109), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U147 (
	.A(la_write[26]),
	.B(n1200),
	.C(la_input[26]),
	.Y(n108), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U148 (
	.A(n109),
	.B(n108),
	.Y(N152), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U149 (
	.A1(n119),
	.A2(wdata[27]),
	.B1(n118),
	.B2(N38),
	.Y(n111), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U150 (
	.A(la_write[27]),
	.B(n1200),
	.C(la_input[27]),
	.Y(n1101), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U151 (
	.A(n111),
	.B(n1101),
	.Y(N153), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U152 (
	.A1(n119),
	.A2(wdata[28]),
	.B1(n118),
	.B2(N39),
	.Y(n113), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U153 (
	.A(la_write[28]),
	.B(n1200),
	.C(la_input[28]),
	.Y(n112), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U154 (
	.A(n113),
	.B(n112),
	.Y(N154), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U155 (
	.A1(n119),
	.A2(wdata[29]),
	.B1(n118),
	.B2(N40),
	.Y(n115), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U156 (
	.A(la_write[29]),
	.B(n1200),
	.C(la_input[29]),
	.Y(n114), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U157 (
	.A(n115),
	.B(n114),
	.Y(N155), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U158 (
	.A1(n119),
	.A2(wdata[30]),
	.B1(n118),
	.B2(N41),
	.Y(n117), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U159 (
	.A(la_write[30]),
	.B(n1200),
	.C(la_input[30]),
	.Y(n116), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U160 (
	.A(n117),
	.B(n116),
	.Y(N156), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U161 (
	.A1(n119),
	.A2(wdata[31]),
	.B1(n118),
	.B2(N42),
	.Y(n122), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U162 (
	.A(la_write[31]),
	.B(n1200),
	.C(la_input[31]),
	.Y(n1211), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U163 (
	.A(n122),
	.B(n1211),
	.Y(N157), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U164 (
	.A(reset),
	.B(n1230),
	.Y(N158), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
endmodule

module user_proj_example (
	wb_clk_i, 
	wb_rst_i, 
	wbs_stb_i, 
	wbs_cyc_i, 
	wbs_we_i, 
	wbs_sel_i, 
	wbs_dat_i, 
	wbs_adr_i, 
	wbs_ack_o, 
	wbs_dat_o, 
	la_data_in, 
	la_data_out, 
	la_oenb, 
	io_in, 
	io_out, 
	io_oeb, 
	irq, 
	vssd1, 
	vccd1);
   input wb_clk_i;
   input wb_rst_i;
   input wbs_stb_i;
   input wbs_cyc_i;
   input wbs_we_i;
   input [3:0] wbs_sel_i;
   input [31:0] wbs_dat_i;
   input [31:0] wbs_adr_i;
   output wbs_ack_o;
   output [31:0] wbs_dat_o;
   input [127:0] la_data_in;
   output [127:0] la_data_out;
   input [127:0] la_oenb;
   input [37:0] io_in;
   output [37:0] io_out;
   output [37:0] io_oeb;
   output [2:0] irq;
   inout vssd1;
   inout vccd1;

   // Internal wires
   wire vssa2;
   wire vssa1;
   wire vssd2;
   wire vdda2;
   wire vdda1;
   wire vccd2;
   wire FE_OFN3_n108;
   wire FE_OFN2_n108;
   wire FE_OFN1_n108;
   wire FE_RN_34;
   wire FE_RN_24;
   wire FE_RN_22;
   wire FE_RN_5;
   wire valid;
   wire N4;
   wire clk;
   wire n108;
   wire [3:0] wstrb;
   wire [31:0] la_write;

   assign FE_RN_5 = FE_RN_24 ;
   assign FE_RN_24 = FE_RN_22 ;
   assign io_oeb[36] = FE_RN_22 ;
   assign io_oeb[34] = FE_RN_22 ;
   assign io_oeb[35] = FE_RN_22 ;
   assign FE_RN_34 = FE_RN_22 ;
   assign io_out[0] = la_data_out[0] ;
   assign io_out[1] = la_data_out[1] ;
   assign io_out[2] = la_data_out[2] ;
   assign io_out[3] = la_data_out[3] ;
   assign io_out[4] = la_data_out[4] ;
   assign io_out[5] = la_data_out[5] ;
   assign io_out[6] = la_data_out[6] ;
   assign io_out[7] = la_data_out[7] ;
   assign io_out[8] = la_data_out[8] ;
   assign io_out[9] = la_data_out[9] ;
   assign io_out[10] = la_data_out[10] ;
   assign io_out[11] = la_data_out[11] ;
   assign io_out[12] = la_data_out[12] ;
   assign io_out[13] = la_data_out[13] ;
   assign io_out[14] = la_data_out[14] ;
   assign io_out[15] = la_data_out[15] ;
   assign io_out[16] = la_data_out[16] ;
   assign io_out[17] = la_data_out[17] ;
   assign io_out[18] = la_data_out[18] ;
   assign io_out[19] = la_data_out[19] ;
   assign io_out[20] = la_data_out[20] ;
   assign io_out[21] = la_data_out[21] ;
   assign io_out[22] = la_data_out[22] ;
   assign io_out[23] = la_data_out[23] ;
   assign io_out[24] = la_data_out[24] ;
   assign io_out[25] = la_data_out[25] ;
   assign io_out[26] = la_data_out[26] ;
   assign io_out[27] = la_data_out[27] ;
   assign io_out[28] = la_data_out[28] ;
   assign io_out[29] = la_data_out[29] ;
   assign io_out[30] = la_data_out[30] ;
   assign io_out[31] = la_data_out[31] ;
   assign io_oeb[32] = io_oeb[33] ;
   assign io_oeb[31] = io_oeb[33] ;
   assign io_oeb[30] = io_oeb[33] ;
   assign io_oeb[29] = io_oeb[33] ;
   assign io_oeb[28] = io_oeb[33] ;
   assign io_oeb[27] = io_oeb[33] ;
   assign io_oeb[26] = io_oeb[33] ;
   assign io_oeb[25] = io_oeb[33] ;
   assign io_oeb[24] = io_oeb[33] ;
   assign io_oeb[23] = io_oeb[33] ;
   assign io_oeb[22] = io_oeb[33] ;
   assign io_oeb[21] = io_oeb[33] ;
   assign io_oeb[20] = io_oeb[33] ;
   assign io_oeb[19] = io_oeb[33] ;
   assign io_oeb[18] = io_oeb[33] ;
   assign io_oeb[17] = io_oeb[33] ;
   assign io_oeb[16] = io_oeb[33] ;
   assign io_oeb[15] = io_oeb[33] ;
   assign io_oeb[14] = io_oeb[33] ;
   assign io_oeb[13] = io_oeb[33] ;
   assign io_oeb[12] = io_oeb[33] ;
   assign io_oeb[11] = io_oeb[33] ;
   assign io_oeb[10] = io_oeb[33] ;
   assign io_oeb[9] = io_oeb[33] ;
   assign io_oeb[8] = io_oeb[33] ;
   assign io_oeb[7] = io_oeb[33] ;
   assign io_oeb[6] = io_oeb[33] ;
   assign io_oeb[5] = io_oeb[33] ;
   assign io_oeb[4] = io_oeb[33] ;
   assign io_oeb[3] = io_oeb[33] ;
   assign io_oeb[2] = io_oeb[33] ;
   assign io_oeb[1] = io_oeb[33] ;
   assign io_oeb[0] = io_oeb[33] ;

   // Module instantiations
   sky130_fd_sc_hd__clkinvlp_2 FE_OFC3_n108 (
	.A(FE_OFN1_n108),
	.Y(FE_OFN3_n108), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_4 FE_OFC2_n108 (
	.A(FE_OFN1_n108),
	.Y(FE_OFN2_n108), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 FE_OFC1_n108 (
	.A(n108),
	.Y(FE_OFN1_n108), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_6 FE_OFC0_io_oeb_0 (
	.A(FE_RN_34),
	.X(io_oeb[33]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__mux2_2 FE_RC_0_0 (
	.A0(la_data_in[65]),
	.A1(wb_rst_i),
	.S(la_oenb[65]),
	.X(FE_RN_22), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   user_proj_example_counter_BITS32_0 counter (
	.clk(clk),
	.reset(FE_RN_5),
	.valid(valid),
	.wstrb(wstrb),
	.wdata(wbs_dat_i),
	.la_write(la_write),
	.la_input({ la_data_in[63],
		la_data_in[62],
		la_data_in[61],
		la_data_in[60],
		la_data_in[59],
		la_data_in[58],
		la_data_in[57],
		la_data_in[56],
		la_data_in[55],
		la_data_in[54],
		la_data_in[53],
		la_data_in[52],
		la_data_in[51],
		la_data_in[50],
		la_data_in[49],
		la_data_in[48],
		la_data_in[47],
		la_data_in[46],
		la_data_in[45],
		la_data_in[44],
		la_data_in[43],
		la_data_in[42],
		la_data_in[41],
		la_data_in[40],
		la_data_in[39],
		la_data_in[38],
		la_data_in[37],
		la_data_in[36],
		la_data_in[35],
		la_data_in[34],
		la_data_in[33],
		la_data_in[32] }),
	.ready(wbs_ack_o),
	.rdata(wbs_dat_o),
	.count({ la_data_out[31],
		la_data_out[30],
		la_data_out[29],
		la_data_out[28],
		la_data_out[27],
		la_data_out[26],
		la_data_out[25],
		la_data_out[24],
		la_data_out[23],
		la_data_out[22],
		la_data_out[21],
		la_data_out[20],
		la_data_out[19],
		la_data_out[18],
		la_data_out[17],
		la_data_out[16],
		la_data_out[15],
		la_data_out[14],
		la_data_out[13],
		la_data_out[12],
		la_data_out[11],
		la_data_out[10],
		la_data_out[9],
		la_data_out[8],
		la_data_out[7],
		la_data_out[6],
		la_data_out[5],
		la_data_out[4],
		la_data_out[3],
		la_data_out[2],
		la_data_out[1],
		la_data_out[0] }), 
	.vccd1(vccd1), 
	.vssd1(vssd1));
   sky130_fd_sc_hd__mux2_8 U43 (
	.A0(wb_clk_i),
	.A1(la_data_in[64]),
	.S(N4),
	.X(clk), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__and2_1 U48 (
	.A(wbs_stb_i),
	.B(wbs_cyc_i),
	.X(valid), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__conb_1 U49 (
	.HI(n108), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U50 (
	.A(FE_OFN2_n108),
	.Y(irq[0]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U51 (
	.A(n108),
	.Y(irq[1]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U52 (
	.A(n108),
	.Y(irq[2]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U53 (
	.A(n108),
	.Y(io_oeb[37]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U54 (
	.A(n108),
	.Y(io_out[32]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U55 (
	.A(n108),
	.Y(io_out[33]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U56 (
	.A(n108),
	.Y(io_out[34]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U57 (
	.A(n108),
	.Y(io_out[35]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U58 (
	.A(n108),
	.Y(io_out[36]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U59 (
	.A(n108),
	.Y(io_out[37]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U60 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[32]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U61 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[33]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U62 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[34]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U63 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[35]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U64 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[36]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U65 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[37]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U66 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[38]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U67 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[39]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U68 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[40]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U69 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[41]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U70 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[42]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U71 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[43]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U72 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[44]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U73 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[45]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U74 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[46]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U75 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[47]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U76 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[48]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U77 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[49]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U78 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[50]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U79 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[51]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U80 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[52]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U81 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[53]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U82 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[54]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U83 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[55]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U84 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[56]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U85 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[57]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U86 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[58]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U87 (
	.A(n108),
	.Y(la_data_out[59]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U88 (
	.A(n108),
	.Y(la_data_out[60]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U89 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[61]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U90 (
	.A(FE_OFN3_n108),
	.Y(la_data_out[62]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U91 (
	.A(FE_OFN3_n108),
	.Y(la_data_out[63]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U92 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[64]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U93 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[65]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U94 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[66]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U95 (
	.A(n108),
	.Y(la_data_out[67]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U96 (
	.A(n108),
	.Y(la_data_out[68]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U97 (
	.A(n108),
	.Y(la_data_out[69]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U98 (
	.A(n108),
	.Y(la_data_out[70]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U99 (
	.A(n108),
	.Y(la_data_out[71]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U100 (
	.A(n108),
	.Y(la_data_out[72]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U101 (
	.A(n108),
	.Y(la_data_out[73]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U102 (
	.A(n108),
	.Y(la_data_out[74]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U103 (
	.A(n108),
	.Y(la_data_out[75]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U104 (
	.A(n108),
	.Y(la_data_out[76]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U105 (
	.A(n108),
	.Y(la_data_out[77]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U106 (
	.A(n108),
	.Y(la_data_out[78]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U107 (
	.A(n108),
	.Y(la_data_out[79]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U108 (
	.A(n108),
	.Y(la_data_out[80]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U109 (
	.A(FE_OFN3_n108),
	.Y(la_data_out[81]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U110 (
	.A(FE_OFN3_n108),
	.Y(la_data_out[82]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U111 (
	.A(n108),
	.Y(la_data_out[83]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U112 (
	.A(n108),
	.Y(la_data_out[84]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U113 (
	.A(n108),
	.Y(la_data_out[85]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U114 (
	.A(n108),
	.Y(la_data_out[86]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U115 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[87]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U116 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[88]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U117 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[89]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U118 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[90]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U119 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[91]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U120 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[92]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U121 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[93]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U122 (
	.A(n108),
	.Y(la_data_out[94]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U123 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[95]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U124 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[96]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U125 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[97]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U126 (
	.A(n108),
	.Y(la_data_out[98]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U127 (
	.A(n108),
	.Y(la_data_out[99]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U128 (
	.A(n108),
	.Y(la_data_out[100]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U129 (
	.A(n108),
	.Y(la_data_out[101]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U130 (
	.A(FE_OFN2_n108),
	.Y(la_data_out[102]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U131 (
	.A(n108),
	.Y(la_data_out[103]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U132 (
	.A(n108),
	.Y(la_data_out[104]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U133 (
	.A(n108),
	.Y(la_data_out[105]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U134 (
	.A(n108),
	.Y(la_data_out[106]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U135 (
	.A(n108),
	.Y(la_data_out[107]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U136 (
	.A(n108),
	.Y(la_data_out[108]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U137 (
	.A(n108),
	.Y(la_data_out[109]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U138 (
	.A(n108),
	.Y(la_data_out[110]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U139 (
	.A(n108),
	.Y(la_data_out[111]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U140 (
	.A(n108),
	.Y(la_data_out[112]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U141 (
	.A(n108),
	.Y(la_data_out[113]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U142 (
	.A(n108),
	.Y(la_data_out[114]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U143 (
	.A(n108),
	.Y(la_data_out[115]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U144 (
	.A(n108),
	.Y(la_data_out[116]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U145 (
	.A(n108),
	.Y(la_data_out[117]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U146 (
	.A(n108),
	.Y(la_data_out[118]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U147 (
	.A(n108),
	.Y(la_data_out[119]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U148 (
	.A(n108),
	.Y(la_data_out[120]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U149 (
	.A(n108),
	.Y(la_data_out[121]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U150 (
	.A(n108),
	.Y(la_data_out[122]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U151 (
	.A(n108),
	.Y(la_data_out[123]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U152 (
	.A(n108),
	.Y(la_data_out[124]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U153 (
	.A(n108),
	.Y(la_data_out[125]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U154 (
	.A(n108),
	.Y(la_data_out[126]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U155 (
	.A(n108),
	.Y(la_data_out[127]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__and2_0 U156 (
	.A(wbs_we_i),
	.B(wbs_sel_i[3]),
	.X(wstrb[3]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__and2_0 U157 (
	.A(wbs_we_i),
	.B(wbs_sel_i[2]),
	.X(wstrb[2]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__and2_0 U158 (
	.A(wbs_we_i),
	.B(wbs_sel_i[1]),
	.X(wstrb[1]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__and2_0 U159 (
	.A(wbs_we_i),
	.B(wbs_sel_i[0]),
	.X(wstrb[0]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U162 (
	.A(la_oenb[64]),
	.Y(N4), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U228 (
	.A(valid),
	.B(la_oenb[63]),
	.Y(la_write[31]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U229 (
	.A(valid),
	.B(la_oenb[62]),
	.Y(la_write[30]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U230 (
	.A(valid),
	.B(la_oenb[61]),
	.Y(la_write[29]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U231 (
	.A(valid),
	.B(la_oenb[60]),
	.Y(la_write[28]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U232 (
	.A(valid),
	.B(la_oenb[59]),
	.Y(la_write[27]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U233 (
	.A(valid),
	.B(la_oenb[58]),
	.Y(la_write[26]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U234 (
	.A(valid),
	.B(la_oenb[57]),
	.Y(la_write[25]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U235 (
	.A(valid),
	.B(la_oenb[56]),
	.Y(la_write[24]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U236 (
	.A(valid),
	.B(la_oenb[55]),
	.Y(la_write[23]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U237 (
	.A(valid),
	.B(la_oenb[54]),
	.Y(la_write[22]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U238 (
	.A(valid),
	.B(la_oenb[53]),
	.Y(la_write[21]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U239 (
	.A(valid),
	.B(la_oenb[52]),
	.Y(la_write[20]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U240 (
	.A(valid),
	.B(la_oenb[51]),
	.Y(la_write[19]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U241 (
	.A(valid),
	.B(la_oenb[50]),
	.Y(la_write[18]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U242 (
	.A(valid),
	.B(la_oenb[49]),
	.Y(la_write[17]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U243 (
	.A(valid),
	.B(la_oenb[48]),
	.Y(la_write[16]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U244 (
	.A(valid),
	.B(la_oenb[47]),
	.Y(la_write[15]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U245 (
	.A(valid),
	.B(la_oenb[46]),
	.Y(la_write[14]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U246 (
	.A(valid),
	.B(la_oenb[45]),
	.Y(la_write[13]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U247 (
	.A(valid),
	.B(la_oenb[44]),
	.Y(la_write[12]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U248 (
	.A(valid),
	.B(la_oenb[43]),
	.Y(la_write[11]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U249 (
	.A(valid),
	.B(la_oenb[42]),
	.Y(la_write[10]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U250 (
	.A(valid),
	.B(la_oenb[41]),
	.Y(la_write[9]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U251 (
	.A(valid),
	.B(la_oenb[40]),
	.Y(la_write[8]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U252 (
	.A(valid),
	.B(la_oenb[39]),
	.Y(la_write[7]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U253 (
	.A(valid),
	.B(la_oenb[38]),
	.Y(la_write[6]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U254 (
	.A(valid),
	.B(la_oenb[37]),
	.Y(la_write[5]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U255 (
	.A(valid),
	.B(la_oenb[36]),
	.Y(la_write[4]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U256 (
	.A(valid),
	.B(la_oenb[35]),
	.Y(la_write[3]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U257 (
	.A(valid),
	.B(la_oenb[34]),
	.Y(la_write[2]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U258 (
	.A(valid),
	.B(la_oenb[33]),
	.Y(la_write[1]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U259 (
	.A(valid),
	.B(la_oenb[32]),
	.Y(la_write[0]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
endmodule

