/*
###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID localhost.localdomain)
#  Generated on:      Fri Jun 11 09:03:14 2021
#  Design:            user_project_wrapper
###############################################################
*/
module user_project_wrapper_SNPS_CLOCK_GATE_HIGH_counter_BITS32_0 (
	EN, 
	TE, 
	ENCLK, 
	ENCLK_clone1, 
	ENCLK_clone2, 
	ENCLK_clone3, 
	CLK, 
	vccd1, 
	vssd1);
   input EN;
   input TE;
   output ENCLK;
   output ENCLK_clone1;
   output ENCLK_clone2;
   output ENCLK_clone3;
   input CLK;
   inout vccd1;
   inout vssd1;

   // Module instantiations
   sky130_fd_sc_hd__sdlclkp_4 latch_clone_11 (
	.CLK(CLK),
	.GATE(EN),
	.GCLK(ENCLK_clone3),
	.SCE(TE), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__sdlclkp_4 latch_clone_10 (
	.CLK(CLK),
	.GATE(EN),
	.GCLK(ENCLK_clone2),
	.SCE(TE), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__sdlclkp_2 latch_clone_9 (
	.CLK(CLK),
	.GATE(EN),
	.GCLK(ENCLK_clone1),
	.SCE(TE), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__sdlclkp_4 latch_clone (
	.CLK(CLK),
	.GATE(EN),
	.GCLK(ENCLK),
	.SCE(TE), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
endmodule

module user_project_wrapper_SNPS_CLOCK_GATE_HIGH_counter_BITS32_4 (
	CLK, 
	EN, 
	ENCLK, 
	TE, 
	vccd1, 
	vssd1);
   input CLK;
   input EN;
   output ENCLK;
   input TE;
   inout vccd1;
   inout vssd1;

   // Module instantiations
   sky130_fd_sc_hd__sdlclkp_4 latch (
	.CLK(CLK),
	.GATE(EN),
	.GCLK(ENCLK),
	.SCE(TE), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
endmodule

module user_project_wrapper_SNPS_CLOCK_GATE_HIGH_counter_BITS32_3 (
	CLK, 
	EN, 
	ENCLK, 
	TE, 
	vccd1, 
	vssd1);
   input CLK;
   input EN;
   output ENCLK;
   input TE;
   inout vccd1;
   inout vssd1;

   // Module instantiations
   sky130_fd_sc_hd__sdlclkp_4 latch (
	.CLK(CLK),
	.GATE(EN),
	.GCLK(ENCLK),
	.SCE(TE), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
endmodule

module user_project_wrapper_SNPS_CLOCK_GATE_HIGH_counter_BITS32_2 (
	CLK, 
	EN, 
	ENCLK, 
	TE, 
	vccd1, 
	vssd1);
   input CLK;
   input EN;
   output ENCLK;
   input TE;
   inout vccd1;
   inout vssd1;

   // Module instantiations
   sky130_fd_sc_hd__sdlclkp_4 latch (
	.CLK(CLK),
	.GATE(EN),
	.GCLK(ENCLK),
	.SCE(TE), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
endmodule

module user_project_wrapper_SNPS_CLOCK_GATE_HIGH_counter_BITS32_1 (
	CLK, 
	EN, 
	ENCLK, 
	TE, 
	vccd1, 
	vssd1);
   input CLK;
   input EN;
   output ENCLK;
   input TE;
   inout vccd1;
   inout vssd1;

   // Module instantiations
   sky130_fd_sc_hd__sdlclkp_4 latch (
	.CLK(CLK),
	.GATE(EN),
	.GCLK(ENCLK),
	.SCE(TE), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
endmodule

module user_project_wrapper_counter_BITS32_DW01_inc_J1_0_0 (
	A, 
	SUM, 
	vccd1, 
	vssd1);
   input [31:0] A;
   output [31:0] SUM;
   inout vccd1;
   inout vssd1;

   // Internal wires
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n111;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;

   // Module instantiations
   sky130_fd_sc_hd__ha_2 U35 (
	.A(A[27]),
	.B(n125),
	.COUT(n126),
	.SUM(SUM[27]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U36 (
	.A(A[23]),
	.B(n121),
	.COUT(n122),
	.SUM(SUM[23]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U37 (
	.A(A[18]),
	.B(n116),
	.COUT(n117),
	.SUM(SUM[18]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U38 (
	.A(A[14]),
	.B(n112),
	.COUT(n113),
	.SUM(SUM[14]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U39 (
	.A(A[10]),
	.B(n108),
	.COUT(n109),
	.SUM(SUM[10]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U40 (
	.A(A[5]),
	.B(n103),
	.COUT(n104),
	.SUM(SUM[5]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U41 (
	.A(A[1]),
	.B(A[0]),
	.COUT(n100),
	.SUM(SUM[1]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U42 (
	.A(A[0]),
	.Y(SUM[0]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__xor2_1 U43 (
	.A(n99),
	.B(A[31]),
	.X(SUM[31]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U44 (
	.A(A[2]),
	.B(n100),
	.COUT(n101),
	.SUM(SUM[2]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U45 (
	.A(A[3]),
	.B(n101),
	.COUT(n102),
	.SUM(SUM[3]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U46 (
	.A(A[4]),
	.B(n102),
	.COUT(n103),
	.SUM(SUM[4]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U47 (
	.A(A[6]),
	.B(n104),
	.COUT(n105),
	.SUM(SUM[6]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U48 (
	.A(A[7]),
	.B(n105),
	.COUT(n106),
	.SUM(SUM[7]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U49 (
	.A(A[8]),
	.B(n106),
	.COUT(n107),
	.SUM(SUM[8]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U50 (
	.A(A[9]),
	.B(n107),
	.COUT(n108),
	.SUM(SUM[9]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U51 (
	.A(A[11]),
	.B(n109),
	.COUT(n110),
	.SUM(SUM[11]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U52 (
	.A(A[12]),
	.B(n110),
	.COUT(n111),
	.SUM(SUM[12]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U53 (
	.A(A[13]),
	.B(n111),
	.COUT(n112),
	.SUM(SUM[13]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U54 (
	.A(A[15]),
	.B(n113),
	.COUT(n114),
	.SUM(SUM[15]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U55 (
	.A(A[16]),
	.B(n114),
	.COUT(n115),
	.SUM(SUM[16]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U56 (
	.A(A[17]),
	.B(n115),
	.COUT(n116),
	.SUM(SUM[17]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U57 (
	.A(A[19]),
	.B(n117),
	.COUT(n118),
	.SUM(SUM[19]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U58 (
	.A(A[20]),
	.B(n118),
	.COUT(n119),
	.SUM(SUM[20]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U59 (
	.A(A[21]),
	.B(n119),
	.COUT(n120),
	.SUM(SUM[21]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U60 (
	.A(A[22]),
	.B(n120),
	.COUT(n121),
	.SUM(SUM[22]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U61 (
	.A(A[24]),
	.B(n122),
	.COUT(n123),
	.SUM(SUM[24]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U62 (
	.A(A[25]),
	.B(n123),
	.COUT(n124),
	.SUM(SUM[25]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U63 (
	.A(A[26]),
	.B(n124),
	.COUT(n125),
	.SUM(SUM[26]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U64 (
	.A(A[28]),
	.B(n126),
	.COUT(n127),
	.SUM(SUM[28]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U65 (
	.A(A[29]),
	.B(n127),
	.COUT(n128),
	.SUM(SUM[29]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__ha_2 U66 (
	.A(A[30]),
	.B(n128),
	.COUT(n99),
	.SUM(SUM[30]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
endmodule

module user_project_wrapper_counter_BITS32_0 (
	reset, 
	valid, 
	wstrb, 
	wdata, 
	la_write, 
	la_input, 
	ready, 
	rdata, 
	count, 
	FE_OFN0_io_out_26, 
	FE_OFN1_io_out_24, 
	FE_OFN2_io_out_23, 
	FE_OFN3_io_out_22, 
	FE_OFN4_io_out_21, 
	FE_OFN5_io_out_8, 
	FE_OFN6_io_out_7, 
	FE_OFN7_io_out_6, 
	FE_OFN8_io_out_5, 
	FE_OFN9_io_out_4, 
	FE_OFN10_io_out_3, 
	FE_OFN11_io_out_2, 
	clk_clone1, 
	clk_clone2, 
	clk, 
	vccd1, 
	vssd1);
   input reset;
   input valid;
   input [3:0] wstrb;
   input [31:0] wdata;
   input [31:0] la_write;
   input [31:0] la_input;
   output ready;
   output [31:0] rdata;
   output [31:0] count;
   output FE_OFN0_io_out_26;
   output FE_OFN1_io_out_24;
   output FE_OFN2_io_out_23;
   output FE_OFN3_io_out_22;
   output FE_OFN4_io_out_21;
   output FE_OFN5_io_out_8;
   output FE_OFN6_io_out_7;
   output FE_OFN7_io_out_6;
   output FE_OFN8_io_out_5;
   output FE_OFN9_io_out_4;
   output FE_OFN10_io_out_3;
   output FE_OFN11_io_out_2;
   input clk_clone1;
   input clk_clone2;
   input clk;
   inout vccd1;
   inout vssd1;

   // Internal wires
   wire CTS_8;
   wire CTS_7;
   wire CTS_4;
   wire CTS_3;
   wire CTS_2;
   wire CTS_1;
   wire FE_OFN67_io_out_0;
   wire FE_OFN65_io_out_1;
   wire FE_OFN62_io_out_2;
   wire FE_OFN59_io_out_3;
   wire FE_OFN56_io_out_4;
   wire FE_OFN53_io_out_5;
   wire FE_OFN50_io_out_6;
   wire FE_OFN47_io_out_7;
   wire FE_OFN44_io_out_8;
   wire FE_OFN27_io_out_21;
   wire FE_OFN24_io_out_22;
   wire FE_OFN21_io_out_23;
   wire FE_OFN17_io_out_24;
   wire FE_OFN15_io_out_25;
   wire FE_OFN13_io_out_25;
   wire FE_OFN10_io_out_26;
   wire FE_OFN8_io_out_27;
   wire FE_OFN6_io_out_28;
   wire FE_OFN4_io_out_29;
   wire FE_OFN2_io_out_30;
   wire FE_OFN0_io_out_31;
   wire n_Logic0_;
   wire N11;
   wire N12;
   wire N13;
   wire N14;
   wire N15;
   wire N16;
   wire N17;
   wire N18;
   wire N19;
   wire N20;
   wire N21;
   wire N22;
   wire N23;
   wire N24;
   wire N25;
   wire N26;
   wire N27;
   wire N28;
   wire N29;
   wire N30;
   wire N31;
   wire N32;
   wire N33;
   wire N34;
   wire N35;
   wire N36;
   wire N37;
   wire N38;
   wire N39;
   wire N40;
   wire N41;
   wire N42;
   wire N120;
   wire N123;
   wire N124;
   wire N125;
   wire N126;
   wire N127;
   wire N128;
   wire N129;
   wire N130;
   wire N132;
   wire N133;
   wire N134;
   wire N135;
   wire N136;
   wire N137;
   wire N138;
   wire N139;
   wire N141;
   wire N142;
   wire N143;
   wire N144;
   wire N145;
   wire N146;
   wire N147;
   wire N148;
   wire N150;
   wire N151;
   wire N152;
   wire N153;
   wire N154;
   wire N155;
   wire N156;
   wire N157;
   wire N158;
   wire net734;
   wire net737;
   wire net740;
   wire net743;
   wire net746;
   wire net749;
   wire net752;
   wire net755;
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n1100;
   wire n1210;
   wire n131;
   wire n140;
   wire n159;
   wire n160;
   wire n170;
   wire n180;
   wire n190;
   wire n200;
   wire n210;
   wire n220;
   wire n230;
   wire n240;
   wire n250;
   wire n260;
   wire n270;
   wire n280;
   wire n290;
   wire n300;
   wire n310;
   wire n320;
   wire n330;
   wire n360;
   wire n370;
   wire n380;
   wire n390;
   wire n400;
   wire n410;
   wire n420;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n1101;
   wire n111;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n1200;
   wire n1211;
   wire n122;
   wire n1230;
   wire n1240;
   wire n1250;

   // Module instantiations
   sky130_fd_sc_hd__clkinv_4 CTS_cdb_INV_ideal_wb_clock_G0_L3_1 (
	.A(CTS_8),
	.Y(CTS_7), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_2 CTS_cdb_INV_ideal_wb_clock_G0_L2_1 (
	.A(clk),
	.Y(CTS_8), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_8 FE_OFC61_io_out_0 (
	.A(FE_OFN67_io_out_0),
	.X(count[0]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_8 FE_OFC60_io_out_1 (
	.A(FE_OFN65_io_out_1),
	.X(count[1]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 FE_OFC58_io_out_2 (
	.A(count[2]),
	.Y(FE_OFN11_io_out_2), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 FE_OFC57_io_out_2 (
	.A(FE_OFN62_io_out_2),
	.Y(count[2]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 FE_OFC55_io_out_3 (
	.A(count[3]),
	.Y(FE_OFN10_io_out_3), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 FE_OFC54_io_out_3 (
	.A(FE_OFN59_io_out_3),
	.Y(count[3]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 FE_OFC52_io_out_4 (
	.A(count[4]),
	.Y(FE_OFN9_io_out_4), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 FE_OFC51_io_out_4 (
	.A(FE_OFN56_io_out_4),
	.Y(count[4]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 FE_OFC49_io_out_5 (
	.A(count[5]),
	.Y(FE_OFN8_io_out_5), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_4 FE_OFC48_io_out_5 (
	.A(FE_OFN53_io_out_5),
	.Y(count[5]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 FE_OFC46_io_out_6 (
	.A(count[6]),
	.Y(FE_OFN7_io_out_6), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_4 FE_OFC45_io_out_6 (
	.A(FE_OFN50_io_out_6),
	.Y(count[6]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 FE_OFC43_io_out_7 (
	.A(count[7]),
	.Y(FE_OFN6_io_out_7), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_4 FE_OFC42_io_out_7 (
	.A(FE_OFN47_io_out_7),
	.Y(count[7]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 FE_OFC40_io_out_8 (
	.A(count[8]),
	.Y(FE_OFN5_io_out_8), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_4 FE_OFC39_io_out_8 (
	.A(FE_OFN44_io_out_8),
	.Y(count[8]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_4 FE_OFC23_io_out_21 (
	.A(count[21]),
	.Y(FE_OFN4_io_out_21), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_4 FE_OFC22_io_out_21 (
	.A(FE_OFN27_io_out_21),
	.Y(count[21]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_4 FE_OFC20_io_out_22 (
	.A(count[22]),
	.Y(FE_OFN3_io_out_22), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 FE_OFC19_io_out_22 (
	.A(FE_OFN24_io_out_22),
	.Y(count[22]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_4 FE_OFC17_io_out_23 (
	.A(count[23]),
	.Y(FE_OFN2_io_out_23), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_4 FE_OFC16_io_out_23 (
	.A(FE_OFN21_io_out_23),
	.Y(count[23]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 FE_OFC13_io_out_24 (
	.A(count[24]),
	.Y(FE_OFN1_io_out_24), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 FE_OFC12_io_out_24 (
	.A(FE_OFN17_io_out_24),
	.Y(count[24]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 FE_OFC9_io_out_25 (
	.A(count[25]),
	.Y(FE_OFN15_io_out_25), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_4 FE_OFC8_io_out_25 (
	.A(FE_OFN13_io_out_25),
	.Y(count[25]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_4 FE_OFC6_io_out_26 (
	.A(count[26]),
	.Y(FE_OFN0_io_out_26), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 FE_OFC5_io_out_26 (
	.A(FE_OFN10_io_out_26),
	.Y(count[26]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_12 FE_OFC4_io_out_27 (
	.A(FE_OFN8_io_out_27),
	.X(count[27]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_12 FE_OFC3_io_out_28 (
	.A(FE_OFN6_io_out_28),
	.X(count[28]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_8 FE_OFC2_io_out_29 (
	.A(FE_OFN4_io_out_29),
	.X(count[29]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_6 FE_OFC1_io_out_30 (
	.A(FE_OFN2_io_out_30),
	.X(count[30]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_6 FE_OFC0_io_out_31 (
	.A(FE_OFN0_io_out_31),
	.X(count[31]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   user_project_wrapper_SNPS_CLOCK_GATE_HIGH_counter_BITS32_0 clk_gate_rdata_reg (
	.EN(N158),
	.TE(n_Logic0_),
	.ENCLK(CTS_1),
	.ENCLK_clone1(CTS_2),
	.ENCLK_clone2(CTS_3),
	.ENCLK_clone3(CTS_4),
	.CLK(clk_clone1), 
	.vccd1(vccd1), 
	.vssd1(vssd1));
   user_project_wrapper_SNPS_CLOCK_GATE_HIGH_counter_BITS32_4 clk_gate_count_reg (
	.CLK(clk_clone2),
	.EN(net734),
	.ENCLK(net737),
	.TE(n_Logic0_), 
	.vccd1(vccd1), 
	.vssd1(vssd1));
   user_project_wrapper_SNPS_CLOCK_GATE_HIGH_counter_BITS32_3 clk_gate_count_reg_0 (
	.CLK(clk_clone2),
	.EN(net740),
	.ENCLK(net743),
	.TE(n_Logic0_), 
	.vccd1(vccd1), 
	.vssd1(vssd1));
   user_project_wrapper_SNPS_CLOCK_GATE_HIGH_counter_BITS32_2 clk_gate_count_reg_1 (
	.CLK(clk_clone2),
	.EN(net746),
	.ENCLK(net749),
	.TE(n_Logic0_), 
	.vccd1(vccd1), 
	.vssd1(vssd1));
   user_project_wrapper_SNPS_CLOCK_GATE_HIGH_counter_BITS32_1 clk_gate_count_reg_2 (
	.CLK(clk_clone2),
	.EN(net752),
	.ENCLK(net755),
	.TE(n_Logic0_), 
	.vccd1(vccd1), 
	.vssd1(vssd1));
   user_project_wrapper_counter_BITS32_DW01_inc_J1_0_0 add_x_1 (
	.A({ count[31],
		count[30],
		count[29],
		count[28],
		count[27],
		FE_OFN0_io_out_26,
		FE_OFN15_io_out_25,
		FE_OFN1_io_out_24,
		FE_OFN2_io_out_23,
		FE_OFN3_io_out_22,
		FE_OFN4_io_out_21,
		count[20],
		count[19],
		count[18],
		count[17],
		count[16],
		count[15],
		count[14],
		count[13],
		count[12],
		count[11],
		count[10],
		count[9],
		FE_OFN5_io_out_8,
		FE_OFN6_io_out_7,
		FE_OFN7_io_out_6,
		FE_OFN8_io_out_5,
		FE_OFN9_io_out_4,
		FE_OFN10_io_out_3,
		FE_OFN11_io_out_2,
		count[1],
		count[0] }),
	.SUM({ N42,
		N41,
		N40,
		N39,
		N38,
		N37,
		N36,
		N35,
		N34,
		N33,
		N32,
		N31,
		N30,
		N29,
		N28,
		N27,
		N26,
		N25,
		N24,
		N23,
		N22,
		N21,
		N20,
		N19,
		N18,
		N17,
		N16,
		N15,
		N14,
		N13,
		N12,
		N11 }), 
	.vccd1(vccd1), 
	.vssd1(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_0_ (
	.CLK(CTS_2),
	.D(count[0]),
	.Q(rdata[0]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_1_ (
	.CLK(CTS_4),
	.D(count[1]),
	.Q(rdata[1]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_2_ (
	.CLK(CTS_4),
	.D(FE_OFN11_io_out_2),
	.Q(rdata[2]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_3_ (
	.CLK(CTS_4),
	.D(FE_OFN10_io_out_3),
	.Q(rdata[3]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_4_ (
	.CLK(CTS_1),
	.D(FE_OFN9_io_out_4),
	.Q(rdata[4]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_5_ (
	.CLK(CTS_1),
	.D(FE_OFN8_io_out_5),
	.Q(rdata[5]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_6_ (
	.CLK(CTS_1),
	.D(FE_OFN7_io_out_6),
	.Q(rdata[6]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_7_ (
	.CLK(CTS_1),
	.D(FE_OFN6_io_out_7),
	.Q(rdata[7]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_8_ (
	.CLK(CTS_4),
	.D(FE_OFN5_io_out_8),
	.Q(rdata[8]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_9_ (
	.CLK(CTS_1),
	.D(count[9]),
	.Q(rdata[9]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_10_ (
	.CLK(CTS_1),
	.D(count[10]),
	.Q(rdata[10]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_11_ (
	.CLK(CTS_3),
	.D(count[11]),
	.Q(rdata[11]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_12_ (
	.CLK(CTS_3),
	.D(count[12]),
	.Q(rdata[12]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_13_ (
	.CLK(CTS_3),
	.D(count[13]),
	.Q(rdata[13]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_14_ (
	.CLK(CTS_3),
	.D(count[14]),
	.Q(rdata[14]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_15_ (
	.CLK(CTS_3),
	.D(count[15]),
	.Q(rdata[15]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_16_ (
	.CLK(CTS_3),
	.D(count[16]),
	.Q(rdata[16]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_17_ (
	.CLK(CTS_2),
	.D(count[17]),
	.Q(rdata[17]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_18_ (
	.CLK(CTS_2),
	.D(count[18]),
	.Q(rdata[18]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_19_ (
	.CLK(CTS_1),
	.D(count[19]),
	.Q(rdata[19]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_20_ (
	.CLK(CTS_2),
	.D(count[20]),
	.Q(rdata[20]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_21_ (
	.CLK(CTS_1),
	.D(FE_OFN4_io_out_21),
	.Q(rdata[21]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_22_ (
	.CLK(CTS_2),
	.D(FE_OFN3_io_out_22),
	.Q(rdata[22]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_23_ (
	.CLK(CTS_3),
	.D(FE_OFN2_io_out_23),
	.Q(rdata[23]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_24_ (
	.CLK(CTS_3),
	.D(FE_OFN1_io_out_24),
	.Q(rdata[24]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_25_ (
	.CLK(CTS_3),
	.D(FE_OFN15_io_out_25),
	.Q(rdata[25]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_26_ (
	.CLK(CTS_4),
	.D(FE_OFN0_io_out_26),
	.Q(rdata[26]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_27_ (
	.CLK(CTS_1),
	.D(count[27]),
	.Q(rdata[27]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_28_ (
	.CLK(CTS_4),
	.D(count[28]),
	.Q(rdata[28]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_29_ (
	.CLK(CTS_4),
	.D(count[29]),
	.Q(rdata[29]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_30_ (
	.CLK(CTS_4),
	.D(count[30]),
	.Q(rdata[30]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 rdata_reg_31_ (
	.CLK(CTS_4),
	.D(count[31]),
	.Q(rdata[31]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_31_ (
	.CLK(net737),
	.D(n1),
	.Q(FE_OFN0_io_out_31), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_26_ (
	.CLK(net737),
	.D(n6),
	.Q(FE_OFN10_io_out_26), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_27_ (
	.CLK(net737),
	.D(n5),
	.Q(FE_OFN8_io_out_27), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_28_ (
	.CLK(net737),
	.D(n4),
	.Q(FE_OFN6_io_out_28), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_29_ (
	.CLK(net737),
	.D(n3),
	.Q(FE_OFN4_io_out_29), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_30_ (
	.CLK(net737),
	.D(n2),
	.Q(FE_OFN2_io_out_30), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 ready_reg (
	.CLK(CTS_7),
	.D(n330),
	.Q(ready), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_20_ (
	.CLK(net743),
	.D(n1210),
	.Q(count[20]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_21_ (
	.CLK(net743),
	.D(n1100),
	.Q(FE_OFN27_io_out_21), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_22_ (
	.CLK(net743),
	.D(n10),
	.Q(FE_OFN24_io_out_22), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_23_ (
	.CLK(net743),
	.D(n9),
	.Q(FE_OFN21_io_out_23), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_24_ (
	.CLK(net737),
	.D(n8),
	.Q(FE_OFN17_io_out_24), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_25_ (
	.CLK(net737),
	.D(n7),
	.Q(FE_OFN13_io_out_25), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_14_ (
	.CLK(net749),
	.D(n180),
	.Q(count[14]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_15_ (
	.CLK(net749),
	.D(n170),
	.Q(count[15]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_16_ (
	.CLK(net743),
	.D(n160),
	.Q(count[16]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_17_ (
	.CLK(net743),
	.D(n159),
	.Q(count[17]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_18_ (
	.CLK(net743),
	.D(n140),
	.Q(count[18]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_19_ (
	.CLK(net743),
	.D(n131),
	.Q(count[19]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_8_ (
	.CLK(net749),
	.D(n240),
	.Q(FE_OFN44_io_out_8), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_9_ (
	.CLK(net749),
	.D(n230),
	.Q(count[9]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_10_ (
	.CLK(net749),
	.D(n220),
	.Q(count[10]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_11_ (
	.CLK(net749),
	.D(n210),
	.Q(count[11]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_12_ (
	.CLK(net749),
	.D(n200),
	.Q(count[12]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_13_ (
	.CLK(net749),
	.D(n190),
	.Q(count[13]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_2_ (
	.CLK(net755),
	.D(n300),
	.Q(FE_OFN62_io_out_2), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_3_ (
	.CLK(net755),
	.D(n290),
	.Q(FE_OFN59_io_out_3), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_4_ (
	.CLK(net755),
	.D(n280),
	.Q(FE_OFN56_io_out_4), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_5_ (
	.CLK(net755),
	.D(n270),
	.Q(FE_OFN53_io_out_5), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_6_ (
	.CLK(net755),
	.D(n260),
	.Q(FE_OFN50_io_out_6), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_7_ (
	.CLK(net755),
	.D(n250),
	.Q(FE_OFN47_io_out_7), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_1_ (
	.CLK(net755),
	.D(n310),
	.Q(FE_OFN65_io_out_1), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__dfxtp_1 count_reg_0_ (
	.CLK(net755),
	.D(n320),
	.Q(FE_OFN67_io_out_0), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U35 (
	.A(reset),
	.B_N(N120),
	.Y(n330), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U3 (
	.A(reset),
	.B_N(N157),
	.Y(n1), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U4 (
	.A(reset),
	.B_N(N156),
	.Y(n2), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U5 (
	.A(reset),
	.B_N(N155),
	.Y(n3), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U34 (
	.A(reset),
	.B_N(N123),
	.Y(n320), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U26 (
	.A(reset),
	.B_N(N132),
	.Y(n240), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U10 (
	.A(reset),
	.B_N(N150),
	.Y(n8), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U18 (
	.A(reset),
	.B_N(N141),
	.Y(n160), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U17 (
	.A(reset),
	.B_N(N142),
	.Y(n159), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U16 (
	.A(reset),
	.B_N(N143),
	.Y(n140), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U29 (
	.A(reset),
	.B_N(N128),
	.Y(n270), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U30 (
	.A(reset),
	.B_N(N127),
	.Y(n280), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U31 (
	.A(reset),
	.B_N(N126),
	.Y(n290), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U32 (
	.A(reset),
	.B_N(N125),
	.Y(n300), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U21 (
	.A(reset),
	.B_N(N137),
	.Y(n190), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U33 (
	.A(reset),
	.B_N(N124),
	.Y(n310), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U27 (
	.A(reset),
	.B_N(N130),
	.Y(n250), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U24 (
	.A(reset),
	.B_N(N134),
	.Y(n220), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U25 (
	.A(reset),
	.B_N(N133),
	.Y(n230), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U8 (
	.A(reset),
	.B_N(N152),
	.Y(n6), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U15 (
	.A(reset),
	.B_N(N144),
	.Y(n131), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U12 (
	.A(reset),
	.B_N(N147),
	.Y(n10), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U13 (
	.A(reset),
	.B_N(N146),
	.Y(n1100), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U14 (
	.A(reset),
	.B_N(N145),
	.Y(n1210), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U19 (
	.A(reset),
	.B_N(N139),
	.Y(n170), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U20 (
	.A(reset),
	.B_N(N138),
	.Y(n180), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U9 (
	.A(reset),
	.B_N(N151),
	.Y(n7), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U28 (
	.A(reset),
	.B_N(N129),
	.Y(n260), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U11 (
	.A(reset),
	.B_N(N148),
	.Y(n9), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U6 (
	.A(reset),
	.B_N(N154),
	.Y(n4), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U22 (
	.A(reset),
	.B_N(N136),
	.Y(n200), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U23 (
	.A(reset),
	.B_N(N135),
	.Y(n210), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2b_1 U7 (
	.A(reset),
	.B_N(N153),
	.Y(n5), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_4 U38 (
	.A(N120),
	.B(n47),
	.Y(n122), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U39 (
	.A(n67),
	.Y(n83), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U40 (
	.A(n105),
	.Y(n1211), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U41 (
	.A(n1250),
	.Y(N120), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U42 (
	.A(n48),
	.Y(n64), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U43 (
	.A(n86),
	.Y(n102), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__conb_1 U44 (
	.LO(n_Logic0_), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2b_1 U45 (
	.A_N(ready),
	.B(valid),
	.Y(n1250), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor4_1 U46 (
	.A(la_write[11]),
	.B(la_write[10]),
	.C(la_write[9]),
	.D(la_write[8]),
	.Y(n390), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor4_1 U47 (
	.A(la_write[15]),
	.B(la_write[14]),
	.C(la_write[13]),
	.D(la_write[12]),
	.Y(n380), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor4_1 U48 (
	.A(la_write[3]),
	.B(la_write[2]),
	.C(la_write[1]),
	.D(la_write[0]),
	.Y(n370), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor4_1 U49 (
	.A(la_write[7]),
	.B(la_write[6]),
	.C(la_write[5]),
	.D(la_write[4]),
	.Y(n360), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand4_1 U50 (
	.A(n390),
	.B(n380),
	.C(n370),
	.D(n360),
	.Y(n45), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor4_1 U51 (
	.A(la_write[27]),
	.B(la_write[26]),
	.C(la_write[25]),
	.D(la_write[24]),
	.Y(n43), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor4_1 U52 (
	.A(la_write[31]),
	.B(la_write[30]),
	.C(la_write[29]),
	.D(la_write[28]),
	.Y(n420), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor4_1 U53 (
	.A(la_write[19]),
	.B(la_write[18]),
	.C(la_write[17]),
	.D(la_write[16]),
	.Y(n410), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor4_1 U54 (
	.A(la_write[23]),
	.B(la_write[22]),
	.C(la_write[21]),
	.D(la_write[20]),
	.Y(n400), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand4_1 U55 (
	.A(n43),
	.B(n420),
	.C(n410),
	.D(n400),
	.Y(n44), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U56 (
	.A(n45),
	.B(n44),
	.Y(n47), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor3_1 U57 (
	.A(n47),
	.B(reset),
	.C(n1250),
	.Y(n46), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U58 (
	.A(N120),
	.B(wstrb[3]),
	.Y(n105), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U59 (
	.A(n46),
	.B(n105),
	.Y(net734), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U60 (
	.A(N120),
	.B(wstrb[2]),
	.Y(n86), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U61 (
	.A(n46),
	.B(n86),
	.Y(net740), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U62 (
	.A(N120),
	.B(wstrb[1]),
	.Y(n67), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U63 (
	.A(n46),
	.B(n67),
	.Y(net746), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U64 (
	.A(N120),
	.B(wstrb[0]),
	.Y(n48), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U65 (
	.A(n46),
	.B(n48),
	.Y(net752), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U66 (
	.A(la_write[0]),
	.B(la_input[0]),
	.C(n122),
	.Y(n50), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U67 (
	.A(n122),
	.B(n64),
	.Y(n63), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U68 (
	.A1(n64),
	.A2(wdata[0]),
	.B1(n63),
	.B2(N11),
	.Y(n49), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U69 (
	.A(n50),
	.B(n49),
	.Y(N123), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U70 (
	.A1(n64),
	.A2(wdata[1]),
	.B1(n63),
	.B2(N12),
	.Y(n52), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U71 (
	.A(la_write[1]),
	.B(n122),
	.C(la_input[1]),
	.Y(n51), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U72 (
	.A(n52),
	.B(n51),
	.Y(N124), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U73 (
	.A1(n64),
	.A2(wdata[2]),
	.B1(n63),
	.B2(N13),
	.Y(n54), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U74 (
	.A(la_write[2]),
	.B(n122),
	.C(la_input[2]),
	.Y(n53), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U75 (
	.A(n54),
	.B(n53),
	.Y(N125), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U76 (
	.A1(n64),
	.A2(wdata[3]),
	.B1(n63),
	.B2(N14),
	.Y(n56), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U77 (
	.A(la_write[3]),
	.B(n122),
	.C(la_input[3]),
	.Y(n55), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U78 (
	.A(n56),
	.B(n55),
	.Y(N126), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U79 (
	.A1(n64),
	.A2(wdata[4]),
	.B1(n63),
	.B2(N15),
	.Y(n58), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U80 (
	.A(la_write[4]),
	.B(n122),
	.C(la_input[4]),
	.Y(n57), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U81 (
	.A(n58),
	.B(n57),
	.Y(N127), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U82 (
	.A1(n64),
	.A2(wdata[5]),
	.B1(n63),
	.B2(N16),
	.Y(n60), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U83 (
	.A(la_write[5]),
	.B(n122),
	.C(la_input[5]),
	.Y(n59), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U84 (
	.A(n60),
	.B(n59),
	.Y(N128), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U85 (
	.A1(n64),
	.A2(wdata[6]),
	.B1(n63),
	.B2(N17),
	.Y(n62), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U86 (
	.A(la_write[6]),
	.B(n122),
	.C(la_input[6]),
	.Y(n61), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U87 (
	.A(n62),
	.B(n61),
	.Y(N129), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U88 (
	.A1(n64),
	.A2(wdata[7]),
	.B1(n63),
	.B2(N18),
	.Y(n66), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U89 (
	.A(la_write[7]),
	.B(n122),
	.C(la_input[7]),
	.Y(n65), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U90 (
	.A(n66),
	.B(n65),
	.Y(N130), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U91 (
	.A(la_write[8]),
	.B(la_input[8]),
	.C(n122),
	.Y(n69), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U92 (
	.A(n122),
	.B(n83),
	.Y(n82), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U93 (
	.A1(n83),
	.A2(wdata[8]),
	.B1(n82),
	.B2(N19),
	.Y(n68), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U94 (
	.A(n69),
	.B(n68),
	.Y(N132), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U95 (
	.A1(n83),
	.A2(wdata[9]),
	.B1(n82),
	.B2(N20),
	.Y(n71), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U96 (
	.A(la_write[9]),
	.B(n122),
	.C(la_input[9]),
	.Y(n70), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U97 (
	.A(n71),
	.B(n70),
	.Y(N133), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U98 (
	.A1(n83),
	.A2(wdata[10]),
	.B1(n82),
	.B2(N21),
	.Y(n73), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U99 (
	.A(la_write[10]),
	.B(n122),
	.C(la_input[10]),
	.Y(n72), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U100 (
	.A(n73),
	.B(n72),
	.Y(N134), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U101 (
	.A1(n83),
	.A2(wdata[11]),
	.B1(n82),
	.B2(N22),
	.Y(n75), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U102 (
	.A(la_write[11]),
	.B(n122),
	.C(la_input[11]),
	.Y(n74), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U103 (
	.A(n75),
	.B(n74),
	.Y(N135), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U104 (
	.A1(n83),
	.A2(wdata[12]),
	.B1(n82),
	.B2(N23),
	.Y(n77), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U105 (
	.A(la_write[12]),
	.B(n122),
	.C(la_input[12]),
	.Y(n76), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U106 (
	.A(n77),
	.B(n76),
	.Y(N136), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U107 (
	.A1(n83),
	.A2(wdata[13]),
	.B1(n82),
	.B2(N24),
	.Y(n79), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U108 (
	.A(la_write[13]),
	.B(n122),
	.C(la_input[13]),
	.Y(n78), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U109 (
	.A(n79),
	.B(n78),
	.Y(N137), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U110 (
	.A1(n83),
	.A2(wdata[14]),
	.B1(n82),
	.B2(N25),
	.Y(n81), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U111 (
	.A(la_write[14]),
	.B(n122),
	.C(la_input[14]),
	.Y(n80), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U112 (
	.A(n81),
	.B(n80),
	.Y(N138), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U113 (
	.A1(n83),
	.A2(wdata[15]),
	.B1(n82),
	.B2(N26),
	.Y(n85), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U114 (
	.A(la_write[15]),
	.B(n122),
	.C(la_input[15]),
	.Y(n84), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U115 (
	.A(n85),
	.B(n84),
	.Y(N139), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U116 (
	.A(la_write[16]),
	.B(la_input[16]),
	.C(n122),
	.Y(n88), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U117 (
	.A(n122),
	.B(n102),
	.Y(n101), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U118 (
	.A1(n102),
	.A2(wdata[16]),
	.B1(n101),
	.B2(N27),
	.Y(n87), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U119 (
	.A(n88),
	.B(n87),
	.Y(N141), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U120 (
	.A1(n102),
	.A2(wdata[17]),
	.B1(n101),
	.B2(N28),
	.Y(n90), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U121 (
	.A(la_write[17]),
	.B(n122),
	.C(la_input[17]),
	.Y(n89), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U122 (
	.A(n90),
	.B(n89),
	.Y(N142), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U123 (
	.A1(n102),
	.A2(wdata[18]),
	.B1(n101),
	.B2(N29),
	.Y(n92), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U124 (
	.A(la_write[18]),
	.B(n122),
	.C(la_input[18]),
	.Y(n91), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U125 (
	.A(n92),
	.B(n91),
	.Y(N143), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U126 (
	.A1(n102),
	.A2(wdata[19]),
	.B1(n101),
	.B2(N30),
	.Y(n94), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U127 (
	.A(la_write[19]),
	.B(n122),
	.C(la_input[19]),
	.Y(n93), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U128 (
	.A(n94),
	.B(n93),
	.Y(N144), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U129 (
	.A1(n102),
	.A2(wdata[20]),
	.B1(n101),
	.B2(N31),
	.Y(n96), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U130 (
	.A(la_write[20]),
	.B(n122),
	.C(la_input[20]),
	.Y(n95), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U131 (
	.A(n96),
	.B(n95),
	.Y(N145), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U132 (
	.A1(n102),
	.A2(wdata[21]),
	.B1(n101),
	.B2(N32),
	.Y(n98), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U133 (
	.A(la_write[21]),
	.B(n122),
	.C(la_input[21]),
	.Y(n97), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U134 (
	.A(n98),
	.B(n97),
	.Y(N146), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U135 (
	.A1(n102),
	.A2(wdata[22]),
	.B1(n101),
	.B2(N33),
	.Y(n100), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U136 (
	.A(la_write[22]),
	.B(n122),
	.C(la_input[22]),
	.Y(n99), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U137 (
	.A(n100),
	.B(n99),
	.Y(N147), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U138 (
	.A1(n102),
	.A2(wdata[23]),
	.B1(n101),
	.B2(N34),
	.Y(n104), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U139 (
	.A(la_write[23]),
	.B(n122),
	.C(la_input[23]),
	.Y(n103), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U140 (
	.A(n104),
	.B(n103),
	.Y(N148), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U141 (
	.A(la_write[24]),
	.B(la_input[24]),
	.C(n122),
	.Y(n107), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U142 (
	.A(n122),
	.B(n1211),
	.Y(n1200), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U143 (
	.A1(n1211),
	.A2(wdata[24]),
	.B1(n1200),
	.B2(N35),
	.Y(n106), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U144 (
	.A(n107),
	.B(n106),
	.Y(N150), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U145 (
	.A1(n1211),
	.A2(wdata[25]),
	.B1(n1200),
	.B2(N36),
	.Y(n109), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U146 (
	.A(la_write[25]),
	.B(n122),
	.C(la_input[25]),
	.Y(n108), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U147 (
	.A(n109),
	.B(n108),
	.Y(N151), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U148 (
	.A1(n1211),
	.A2(wdata[26]),
	.B1(n1200),
	.B2(N37),
	.Y(n111), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U149 (
	.A(la_write[26]),
	.B(n122),
	.C(la_input[26]),
	.Y(n1101), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U150 (
	.A(n111),
	.B(n1101),
	.Y(N152), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U151 (
	.A1(n1211),
	.A2(wdata[27]),
	.B1(n1200),
	.B2(N38),
	.Y(n113), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U152 (
	.A(la_write[27]),
	.B(n122),
	.C(la_input[27]),
	.Y(n112), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U153 (
	.A(n113),
	.B(n112),
	.Y(N153), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U154 (
	.A1(n1211),
	.A2(wdata[28]),
	.B1(n1200),
	.B2(N39),
	.Y(n115), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U155 (
	.A(la_write[28]),
	.B(n122),
	.C(la_input[28]),
	.Y(n114), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U156 (
	.A(n115),
	.B(n114),
	.Y(N154), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U157 (
	.A1(n1211),
	.A2(wdata[29]),
	.B1(n1200),
	.B2(N40),
	.Y(n117), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U158 (
	.A(la_write[29]),
	.B(n122),
	.C(la_input[29]),
	.Y(n116), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U159 (
	.A(n117),
	.B(n116),
	.Y(N155), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U160 (
	.A1(n1211),
	.A2(wdata[30]),
	.B1(n1200),
	.B2(N41),
	.Y(n119), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U161 (
	.A(la_write[30]),
	.B(n122),
	.C(la_input[30]),
	.Y(n118), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U162 (
	.A(n119),
	.B(n118),
	.Y(N156), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_1 U163 (
	.A1(n1211),
	.A2(wdata[31]),
	.B1(n1200),
	.B2(N42),
	.Y(n1240), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand3_1 U164 (
	.A(la_write[31]),
	.B(n122),
	.C(la_input[31]),
	.Y(n1230), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nand2_1 U165 (
	.A(n1240),
	.B(n1230),
	.Y(N157), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U166 (
	.A(reset),
	.B(n1250),
	.Y(N158), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
endmodule

module user_project_wrapper_user_proj_example_0 (
	wb_clk_i, 
	wb_rst_i, 
	wbs_stb_i, 
	wbs_cyc_i, 
	wbs_we_i, 
	wbs_sel_i, 
	wbs_dat_i, 
	wbs_adr_i, 
	wbs_ack_o, 
	wbs_dat_o, 
	la_data_in, 
	la_data_out, 
	la_oenb, 
	io_in, 
	io_out, 
	io_oeb, 
	irq, 
	vccd1, 
	vssd1);
   input wb_clk_i;
   input wb_rst_i;
   input wbs_stb_i;
   input wbs_cyc_i;
   input wbs_we_i;
   input [3:0] wbs_sel_i;
   input [31:0] wbs_dat_i;
   input [31:0] wbs_adr_i;
   output wbs_ack_o;
   output [31:0] wbs_dat_o;
   input [127:0] la_data_in;
   output [127:0] la_data_out;
   input [127:0] la_oenb;
   input [37:0] io_in;
   output [37:0] io_out;
   output [37:0] io_oeb;
   output [2:0] irq;
   inout vccd1;
   inout vssd1;

   // Internal wires
   wire CTS_3;
   wire CTS_2;
   wire CTS_1;
   wire FE_RN_65;
   wire FE_RN_47;
   wire FE_RN_40;
   wire FE_RN_32;
   wire FE_RN_31;
   wire FE_RN_30;
   wire FE_RN_29;
   wire FE_RN_28;
   wire FE_RN_27;
   wire FE_RN_26;
   wire FE_RN_25;
   wire FE_RN_24;
   wire FE_RN_23;
   wire FE_RN_22;
   wire FE_RN_20;
   wire FE_RN_17;
   wire FE_RN_16;
   wire FE_RN_15;
   wire FE_RN_14;
   wire FE_RN_13;
   wire FE_RN_12;
   wire FE_RN_11;
   wire FE_RN_10;
   wire FE_RN_9;
   wire FE_RN_6;
   wire FE_RN_5;
   wire valid;
   wire N4;
   wire n1;
   wire n2;
   wire [3:0] wstrb;
   wire [31:0] la_write;

   assign io_oeb[26] = FE_RN_65 ;
   assign io_oeb[28] = FE_RN_40 ;
   assign io_oeb[19] = FE_RN_47 ;
   assign io_out[0] = FE_RN_32 ;
   assign io_out[1] = FE_RN_31 ;
   assign io_out[2] = FE_RN_30 ;
   assign io_out[3] = FE_RN_29 ;
   assign io_out[4] = FE_RN_28 ;
   assign io_out[5] = FE_RN_27 ;
   assign io_out[6] = FE_RN_26 ;
   assign io_out[7] = FE_RN_25 ;
   assign io_out[8] = FE_RN_24 ;
   assign io_out[9] = FE_RN_23 ;
   assign io_out[10] = FE_RN_22 ;
   assign io_out[12] = FE_RN_20 ;
   assign io_out[15] = FE_RN_17 ;
   assign io_out[16] = FE_RN_16 ;
   assign io_out[17] = FE_RN_15 ;
   assign io_out[18] = FE_RN_14 ;
   assign io_out[19] = FE_RN_13 ;
   assign io_out[20] = FE_RN_12 ;
   assign io_out[21] = FE_RN_11 ;
   assign io_out[22] = FE_RN_10 ;
   assign io_out[23] = FE_RN_9 ;
   assign io_out[26] = FE_RN_6 ;
   assign io_out[27] = FE_RN_5 ;

   // Module instantiations
   sky130_fd_sc_hd__mux2_8 U43_clone2 (
	.A0(wb_clk_i),
	.A1(la_data_in[64]),
	.S(N4),
	.X(CTS_3), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__mux2_8 U43_clone1 (
	.A0(wb_clk_i),
	.A1(la_data_in[64]),
	.S(N4),
	.X(CTS_2), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__mux2_1 U43_clone (
	.A0(wb_clk_i),
	.A1(la_data_in[64]),
	.S(N4),
	.X(CTS_1), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   user_project_wrapper_counter_BITS32_0 counter (
	.reset(FE_RN_40),
	.valid(valid),
	.wstrb(wstrb),
	.wdata(wbs_dat_i),
	.la_write(la_write),
	.la_input({ la_data_in[63],
		la_data_in[62],
		la_data_in[61],
		la_data_in[60],
		la_data_in[59],
		la_data_in[58],
		la_data_in[57],
		la_data_in[56],
		la_data_in[55],
		la_data_in[54],
		la_data_in[53],
		la_data_in[52],
		la_data_in[51],
		la_data_in[50],
		la_data_in[49],
		la_data_in[48],
		la_data_in[47],
		la_data_in[46],
		la_data_in[45],
		la_data_in[44],
		la_data_in[43],
		la_data_in[42],
		la_data_in[41],
		la_data_in[40],
		la_data_in[39],
		la_data_in[38],
		la_data_in[37],
		la_data_in[36],
		la_data_in[35],
		la_data_in[34],
		la_data_in[33],
		la_data_in[32] }),
	.ready(wbs_ack_o),
	.rdata(wbs_dat_o),
	.count({ la_data_out[31],
		la_data_out[30],
		la_data_out[29],
		la_data_out[28],
		FE_RN_5,
		FE_RN_6,
		la_data_out[25],
		la_data_out[24],
		FE_RN_9,
		FE_RN_10,
		FE_RN_11,
		FE_RN_12,
		FE_RN_13,
		FE_RN_14,
		FE_RN_15,
		FE_RN_16,
		FE_RN_17,
		la_data_out[14],
		la_data_out[13],
		FE_RN_20,
		la_data_out[11],
		FE_RN_22,
		FE_RN_23,
		FE_RN_24,
		FE_RN_25,
		FE_RN_26,
		FE_RN_27,
		FE_RN_28,
		FE_RN_29,
		FE_RN_30,
		FE_RN_31,
		FE_RN_32 }),
	.FE_OFN0_io_out_26(la_data_out[26]),
	.FE_OFN1_io_out_24(io_out[24]),
	.FE_OFN2_io_out_23(la_data_out[23]),
	.FE_OFN3_io_out_22(la_data_out[22]),
	.FE_OFN4_io_out_21(la_data_out[21]),
	.FE_OFN5_io_out_8(la_data_out[8]),
	.FE_OFN6_io_out_7(la_data_out[7]),
	.FE_OFN7_io_out_6(la_data_out[6]),
	.FE_OFN8_io_out_5(la_data_out[5]),
	.FE_OFN9_io_out_4(la_data_out[4]),
	.FE_OFN10_io_out_3(la_data_out[3]),
	.FE_OFN11_io_out_2(la_data_out[2]),
	.clk_clone1(CTS_2),
	.clk_clone2(CTS_3),
	.clk(CTS_1), 
	.vccd1(vccd1), 
	.vssd1(vssd1));
   sky130_fd_sc_hd__clkinvlp_4 U2 (
	.A(n2),
	.Y(FE_RN_47), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_4 U3 (
	.A(n2),
	.Y(FE_RN_40), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__and2_2 U4 (
	.A(wbs_stb_i),
	.B(wbs_cyc_i),
	.X(valid), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U5 (
	.A(la_oenb[65]),
	.Y(n1), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__and2_0 U6 (
	.A(wbs_we_i),
	.B(wbs_sel_i[3]),
	.X(wstrb[3]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__and2_0 U7 (
	.A(wbs_we_i),
	.B(wbs_sel_i[2]),
	.X(wstrb[2]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__and2_0 U8 (
	.A(wbs_we_i),
	.B(wbs_sel_i[1]),
	.X(wstrb[1]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__and2_0 U9 (
	.A(wbs_we_i),
	.B(wbs_sel_i[0]),
	.X(wstrb[0]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_4 U10 (
	.A(n2),
	.Y(FE_RN_65), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_4 U11 (
	.A(la_oenb[64]),
	.Y(N4), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__a22oi_2 U25 (
	.A1(n1),
	.A2(la_data_in[65]),
	.B1(la_oenb[65]),
	.B2(wb_rst_i),
	.Y(n2), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U80 (
	.A(valid),
	.B(la_oenb[63]),
	.Y(la_write[31]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U81 (
	.A(valid),
	.B(la_oenb[62]),
	.Y(la_write[30]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U82 (
	.A(valid),
	.B(la_oenb[61]),
	.Y(la_write[29]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U83 (
	.A(valid),
	.B(la_oenb[60]),
	.Y(la_write[28]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U84 (
	.A(valid),
	.B(la_oenb[59]),
	.Y(la_write[27]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U85 (
	.A(valid),
	.B(la_oenb[58]),
	.Y(la_write[26]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U86 (
	.A(valid),
	.B(la_oenb[57]),
	.Y(la_write[25]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U87 (
	.A(valid),
	.B(la_oenb[56]),
	.Y(la_write[24]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U88 (
	.A(valid),
	.B(la_oenb[55]),
	.Y(la_write[23]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U89 (
	.A(valid),
	.B(la_oenb[54]),
	.Y(la_write[22]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U90 (
	.A(valid),
	.B(la_oenb[53]),
	.Y(la_write[21]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U91 (
	.A(valid),
	.B(la_oenb[52]),
	.Y(la_write[20]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U92 (
	.A(valid),
	.B(la_oenb[51]),
	.Y(la_write[19]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U93 (
	.A(valid),
	.B(la_oenb[50]),
	.Y(la_write[18]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U94 (
	.A(valid),
	.B(la_oenb[49]),
	.Y(la_write[17]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U95 (
	.A(valid),
	.B(la_oenb[48]),
	.Y(la_write[16]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U96 (
	.A(valid),
	.B(la_oenb[47]),
	.Y(la_write[15]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U97 (
	.A(valid),
	.B(la_oenb[46]),
	.Y(la_write[14]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U98 (
	.A(valid),
	.B(la_oenb[45]),
	.Y(la_write[13]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U99 (
	.A(valid),
	.B(la_oenb[44]),
	.Y(la_write[12]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U100 (
	.A(valid),
	.B(la_oenb[43]),
	.Y(la_write[11]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U101 (
	.A(valid),
	.B(la_oenb[42]),
	.Y(la_write[10]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U102 (
	.A(valid),
	.B(la_oenb[41]),
	.Y(la_write[9]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U103 (
	.A(valid),
	.B(la_oenb[40]),
	.Y(la_write[8]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U104 (
	.A(valid),
	.B(la_oenb[39]),
	.Y(la_write[7]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U105 (
	.A(valid),
	.B(la_oenb[38]),
	.Y(la_write[6]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U106 (
	.A(valid),
	.B(la_oenb[37]),
	.Y(la_write[5]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U107 (
	.A(valid),
	.B(la_oenb[36]),
	.Y(la_write[4]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U108 (
	.A(valid),
	.B(la_oenb[35]),
	.Y(la_write[3]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U109 (
	.A(valid),
	.B(la_oenb[34]),
	.Y(la_write[2]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U110 (
	.A(valid),
	.B(la_oenb[33]),
	.Y(la_write[1]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__nor2_1 U111 (
	.A(valid),
	.B(la_oenb[32]),
	.Y(la_write[0]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
endmodule

module user_project_wrapper (
	wb_clk_i, 
	wb_rst_i, 
	wbs_stb_i, 
	wbs_cyc_i, 
	wbs_we_i, 
	wbs_sel_i, 
	wbs_dat_i, 
	wbs_adr_i, 
	wbs_ack_o, 
	wbs_dat_o, 
	la_data_in, 
	la_data_out, 
	la_oenb, 
	io_in, 
	io_out, 
	io_oeb, 
	analog_io, 
	user_clock2, 
	user_irq, 
	vssa2, 
	vssa1, 
	vssd2, 
	vssd1, 
	vdda2, 
	vdda1, 
	vccd2, 
	vccd1);
   input wb_clk_i;
   input wb_rst_i;
   input wbs_stb_i;
   input wbs_cyc_i;
   input wbs_we_i;
   input [3:0] wbs_sel_i;
   input [31:0] wbs_dat_i;
   input [31:0] wbs_adr_i;
   output wbs_ack_o;
   output [31:0] wbs_dat_o;
   input [127:0] la_data_in;
   output [127:0] la_data_out;
   input [127:0] la_oenb;
   input [37:0] io_in;
   output [37:0] io_out;
   output [37:0] io_oeb;
   inout [28:0] analog_io;
   input user_clock2;
   output [2:0] user_irq;
   inout vssa2;
   inout vssa1;
   inout vssd2;
   inout vssd1;
   inout vdda2;
   inout vdda1;
   inout vccd2;
   inout vccd1;

   // Internal wires
   wire FE_RN_48;
   wire FE_RN_47;
   wire FE_RN_46;
   wire FE_RN_45;
   wire FE_RN_44;
   wire FE_RN_43;
   wire FE_RN_42;
   wire FE_RN_41;
   wire FE_RN_40;
   wire FE_RN_39;
   wire FE_RN_38;
   wire FE_RN_37;
   wire FE_RN_36;
   wire FE_RN_35;
   wire FE_RN_34;
   wire FE_RN_33;
   wire FE_RN_32;
   wire FE_RN_31;
   wire FE_RN_30;
   wire FE_RN_29;
   wire FE_RN_28;
   wire FE_RN_27;
   wire FE_RN_26;
   wire FE_RN_25;
   wire FE_RN_24;
   wire FE_RN_23;
   wire FE_RN_22;
   wire FE_RN_21;
   wire FE_RN_20;
   wire FE_RN_19;
   wire FE_RN_18;
   wire FE_RN_17;
   wire FE_RN_16;
   wire FE_OFN69_n365;
   wire FE_RN_15;
   wire FE_RN_14;
   wire FE_OFN63_io_out_2;
   wire FE_OFN60_io_out_3;
   wire FE_OFN57_io_out_4;
   wire FE_OFN54_io_out_5;
   wire FE_OFN51_io_out_6;
   wire FE_OFN48_io_out_7;
   wire FE_OFN45_io_out_8;
   wire FE_RN_13;
   wire FE_RN_12;
   wire FE_RN_11;
   wire FE_RN_10;
   wire FE_RN_9;
   wire FE_RN_8;
   wire FE_RN_7;
   wire FE_RN_6;
   wire FE_OFN31_io_out_20;
   wire FE_OFN30_io_out_20;
   wire FE_OFN28_io_out_21;
   wire FE_OFN25_io_out_22;
   wire FE_OFN22_io_out_23;
   wire FE_OFN20_io_out_24;
   wire FE_OFN18_io_out_24;
   wire FE_OFN14_io_out_25;
   wire FE_OFN11_io_out_26;
   wire FE_RN_5;
   wire FE_RN_4;
   wire FE_RN_3;
   wire FE_RN_2;
   wire FE_RN_1;
   wire n258;
   wire n365;
   wire SYNOPSYS_UNCONNECTED_1;
   wire SYNOPSYS_UNCONNECTED_2;
   wire SYNOPSYS_UNCONNECTED_3;
   wire SYNOPSYS_UNCONNECTED_4;
   wire SYNOPSYS_UNCONNECTED_5;
   wire SYNOPSYS_UNCONNECTED_6;
   wire SYNOPSYS_UNCONNECTED_7;
   wire SYNOPSYS_UNCONNECTED_8;
   wire SYNOPSYS_UNCONNECTED_9;
   wire SYNOPSYS_UNCONNECTED_10;
   wire SYNOPSYS_UNCONNECTED_11;
   wire SYNOPSYS_UNCONNECTED_12;
   wire SYNOPSYS_UNCONNECTED_13;
   wire SYNOPSYS_UNCONNECTED_14;
   wire SYNOPSYS_UNCONNECTED_15;
   wire SYNOPSYS_UNCONNECTED_16;
   wire SYNOPSYS_UNCONNECTED_17;
   wire SYNOPSYS_UNCONNECTED_18;
   wire SYNOPSYS_UNCONNECTED_19;
   wire SYNOPSYS_UNCONNECTED_20;
   wire SYNOPSYS_UNCONNECTED_21;
   wire SYNOPSYS_UNCONNECTED_22;
   wire SYNOPSYS_UNCONNECTED_23;
   wire SYNOPSYS_UNCONNECTED_24;
   wire SYNOPSYS_UNCONNECTED_25;
   wire SYNOPSYS_UNCONNECTED_26;
   wire SYNOPSYS_UNCONNECTED_27;
   wire SYNOPSYS_UNCONNECTED_28;
   wire SYNOPSYS_UNCONNECTED_29;
   wire SYNOPSYS_UNCONNECTED_30;
   wire SYNOPSYS_UNCONNECTED_31;
   wire SYNOPSYS_UNCONNECTED_32;
   wire SYNOPSYS_UNCONNECTED_33;
   wire SYNOPSYS_UNCONNECTED_34;
   wire SYNOPSYS_UNCONNECTED_35;
   wire SYNOPSYS_UNCONNECTED_36;
   wire SYNOPSYS_UNCONNECTED_37;
   wire SYNOPSYS_UNCONNECTED_38;
   wire SYNOPSYS_UNCONNECTED_39;
   wire SYNOPSYS_UNCONNECTED_40;
   wire SYNOPSYS_UNCONNECTED_41;
   wire SYNOPSYS_UNCONNECTED_42;
   wire SYNOPSYS_UNCONNECTED_43;
   wire SYNOPSYS_UNCONNECTED_44;
   wire SYNOPSYS_UNCONNECTED_45;
   wire SYNOPSYS_UNCONNECTED_46;
   wire SYNOPSYS_UNCONNECTED_47;
   wire SYNOPSYS_UNCONNECTED_48;
   wire SYNOPSYS_UNCONNECTED_49;
   wire SYNOPSYS_UNCONNECTED_50;
   wire SYNOPSYS_UNCONNECTED_51;
   wire SYNOPSYS_UNCONNECTED_52;
   wire SYNOPSYS_UNCONNECTED_53;
   wire SYNOPSYS_UNCONNECTED_54;
   wire SYNOPSYS_UNCONNECTED_55;
   wire SYNOPSYS_UNCONNECTED_56;
   wire SYNOPSYS_UNCONNECTED_57;
   wire SYNOPSYS_UNCONNECTED_58;
   wire SYNOPSYS_UNCONNECTED_59;
   wire SYNOPSYS_UNCONNECTED_60;
   wire SYNOPSYS_UNCONNECTED_61;
   wire SYNOPSYS_UNCONNECTED_62;
   wire SYNOPSYS_UNCONNECTED_63;
   wire SYNOPSYS_UNCONNECTED_64;
   wire SYNOPSYS_UNCONNECTED_65;
   wire SYNOPSYS_UNCONNECTED_66;
   wire SYNOPSYS_UNCONNECTED_67;
   wire SYNOPSYS_UNCONNECTED_68;
   wire SYNOPSYS_UNCONNECTED_69;
   wire SYNOPSYS_UNCONNECTED_70;
   wire SYNOPSYS_UNCONNECTED_71;
   wire SYNOPSYS_UNCONNECTED_72;
   wire SYNOPSYS_UNCONNECTED_73;
   wire SYNOPSYS_UNCONNECTED_74;
   wire SYNOPSYS_UNCONNECTED_75;
   wire SYNOPSYS_UNCONNECTED_76;
   wire SYNOPSYS_UNCONNECTED_77;
   wire SYNOPSYS_UNCONNECTED_78;
   wire SYNOPSYS_UNCONNECTED_79;
   wire SYNOPSYS_UNCONNECTED_80;
   wire SYNOPSYS_UNCONNECTED_81;
   wire SYNOPSYS_UNCONNECTED_82;
   wire SYNOPSYS_UNCONNECTED_83;
   wire SYNOPSYS_UNCONNECTED_84;
   wire SYNOPSYS_UNCONNECTED_85;
   wire SYNOPSYS_UNCONNECTED_86;
   wire SYNOPSYS_UNCONNECTED_87;
   wire SYNOPSYS_UNCONNECTED_88;
   wire SYNOPSYS_UNCONNECTED_89;
   wire SYNOPSYS_UNCONNECTED_90;
   wire SYNOPSYS_UNCONNECTED_91;
   wire SYNOPSYS_UNCONNECTED_92;
   wire SYNOPSYS_UNCONNECTED_93;
   wire SYNOPSYS_UNCONNECTED_94;
   wire SYNOPSYS_UNCONNECTED_95;
   wire SYNOPSYS_UNCONNECTED_96;
   wire SYNOPSYS_UNCONNECTED_97;
   wire SYNOPSYS_UNCONNECTED_98;
   wire SYNOPSYS_UNCONNECTED_99;
   wire SYNOPSYS_UNCONNECTED_100;
   wire SYNOPSYS_UNCONNECTED_101;
   wire SYNOPSYS_UNCONNECTED_102;
   wire SYNOPSYS_UNCONNECTED_103;
   wire SYNOPSYS_UNCONNECTED_104;
   wire SYNOPSYS_UNCONNECTED_105;
   wire SYNOPSYS_UNCONNECTED_106;

   assign io_out[31] = la_data_out[31] ;
   assign io_out[30] = la_data_out[30] ;
   assign io_out[29] = la_data_out[29] ;
   assign io_out[28] = la_data_out[28] ;
   assign la_data_out[27] = io_out[27] ;
   assign la_data_out[19] = io_out[19] ;
   assign la_data_out[18] = io_out[18] ;
   assign la_data_out[17] = io_out[17] ;
   assign la_data_out[16] = io_out[16] ;
   assign la_data_out[15] = io_out[15] ;
   assign la_data_out[14] = io_out[14] ;
   assign la_data_out[13] = io_out[13] ;
   assign la_data_out[11] = io_out[11] ;
   assign la_data_out[1] = io_out[1] ;
   assign la_data_out[0] = io_out[0] ;
   assign io_oeb[36] = io_oeb[28] ;
   assign io_oeb[35] = io_oeb[28] ;
   assign io_oeb[34] = io_oeb[28] ;
   assign io_oeb[33] = io_oeb[28] ;
   assign io_oeb[32] = io_oeb[28] ;
   assign io_oeb[31] = io_oeb[28] ;
   assign io_oeb[30] = io_oeb[28] ;
   assign io_oeb[29] = io_oeb[28] ;
   assign io_oeb[27] = FE_RN_30 ;
   assign io_oeb[25] = FE_RN_30 ;
   assign io_oeb[23] = FE_RN_30 ;
   assign io_oeb[21] = FE_RN_30 ;
   assign io_oeb[1] = io_oeb[19] ;
   assign io_oeb[3] = io_oeb[19] ;
   assign io_oeb[5] = io_oeb[19] ;
   assign io_oeb[7] = io_oeb[19] ;
   assign io_oeb[9] = io_oeb[19] ;
   assign io_oeb[11] = io_oeb[19] ;
   assign io_oeb[13] = io_oeb[19] ;
   assign io_oeb[15] = io_oeb[19] ;
   assign io_oeb[17] = io_oeb[19] ;
   assign io_oeb[0] = io_oeb[26] ;
   assign io_oeb[2] = io_oeb[26] ;
   assign io_oeb[4] = io_oeb[22] ;
   assign io_oeb[6] = io_oeb[22] ;
   assign io_oeb[8] = io_oeb[22] ;
   assign io_oeb[10] = io_oeb[22] ;
   assign io_oeb[12] = io_oeb[22] ;
   assign io_oeb[14] = io_oeb[22] ;
   assign io_oeb[16] = io_oeb[22] ;
   assign io_oeb[18] = io_oeb[22] ;
   assign io_oeb[20] = io_oeb[22] ;
   assign io_oeb[24] = io_oeb[22] ;

   // Module instantiations
   sky130_fd_sc_hd__buf_12 FE_OFC67_io_oeb_0 (
	.A(io_oeb[26]),
	.X(io_oeb[22]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_16 FE_OFC66_io_oeb_0 (
	.A(FE_RN_47),
	.X(io_oeb[26]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_12 FE_OFC65_io_oeb_11 (
	.A(FE_RN_30),
	.X(io_oeb[19]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_12 FE_OFC64_io_oeb_11 (
	.A(FE_RN_31),
	.X(FE_RN_30), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_6 FE_OFC63_io_oeb_28 (
	.A(FE_RN_22),
	.X(io_oeb[28]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkbuf_16 FE_OFC62_n365 (
	.A(n365),
	.X(FE_OFN69_n365), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_4 FE_OFC59_io_out_2 (
	.A(FE_OFN63_io_out_2),
	.Y(io_out[2]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_4 FE_OFC56_io_out_3 (
	.A(FE_OFN60_io_out_3),
	.Y(io_out[3]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_4 FE_OFC53_io_out_4 (
	.A(FE_OFN57_io_out_4),
	.Y(io_out[4]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_4 FE_OFC50_io_out_5 (
	.A(FE_OFN54_io_out_5),
	.Y(io_out[5]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_4 FE_OFC47_io_out_6 (
	.A(FE_OFN51_io_out_6),
	.Y(io_out[6]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_4 FE_OFC44_io_out_7 (
	.A(FE_OFN48_io_out_7),
	.Y(io_out[7]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_4 FE_OFC41_io_out_8 (
	.A(FE_OFN45_io_out_8),
	.Y(io_out[8]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_12 FE_OFC38_io_out_9 (
	.A(la_data_out[9]),
	.X(io_out[9]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_12 FE_OFC37_io_out_10 (
	.A(la_data_out[10]),
	.X(io_out[10]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_12 FE_OFC36_io_out_11 (
	.A(FE_RN_13),
	.X(io_out[11]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_12 FE_OFC35_io_out_12 (
	.A(la_data_out[12]),
	.X(io_out[12]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_12 FE_OFC34_io_out_13 (
	.A(FE_RN_12),
	.X(io_out[13]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_12 FE_OFC33_io_out_14 (
	.A(FE_RN_11),
	.X(io_out[14]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_12 FE_OFC32_io_out_15 (
	.A(FE_RN_10),
	.X(io_out[15]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_12 FE_OFC31_io_out_16 (
	.A(FE_RN_9),
	.X(io_out[16]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_12 FE_OFC30_io_out_17 (
	.A(FE_RN_8),
	.X(io_out[17]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_12 FE_OFC29_io_out_18 (
	.A(FE_RN_7),
	.X(io_out[18]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_12 FE_OFC28_io_out_19 (
	.A(FE_RN_6),
	.X(io_out[19]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_4 FE_OFC27_io_out_20 (
	.A(FE_OFN31_io_out_20),
	.Y(io_out[20]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 FE_OFC26_io_out_20 (
	.A(FE_OFN31_io_out_20),
	.Y(la_data_out[20]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_4 FE_OFC25_io_out_20 (
	.A(FE_OFN30_io_out_20),
	.Y(FE_OFN31_io_out_20), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_4 FE_OFC24_io_out_21 (
	.A(FE_OFN28_io_out_21),
	.Y(io_out[21]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_4 FE_OFC21_io_out_22 (
	.A(FE_OFN25_io_out_22),
	.Y(io_out[22]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_4 FE_OFC18_io_out_23 (
	.A(FE_OFN22_io_out_23),
	.Y(io_out[23]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__buf_12 FE_OFC15_io_out_24 (
	.A(FE_OFN20_io_out_24),
	.X(io_out[24]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_4 FE_OFC14_io_out_24 (
	.A(FE_OFN18_io_out_24),
	.Y(la_data_out[24]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_4 FE_OFC11_io_out_25 (
	.A(FE_OFN14_io_out_25),
	.Y(io_out[25]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 FE_OFC10_io_out_25 (
	.A(FE_OFN14_io_out_25),
	.Y(la_data_out[25]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinv_4 FE_OFC7_io_out_26 (
	.A(FE_OFN11_io_out_26),
	.Y(io_out[26]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   user_project_wrapper_user_proj_example_0 mprj (
	.wb_clk_i(wb_clk_i),
	.wb_rst_i(wb_rst_i),
	.wbs_stb_i(wbs_stb_i),
	.wbs_cyc_i(wbs_cyc_i),
	.wbs_we_i(wbs_we_i),
	.wbs_sel_i(wbs_sel_i),
	.wbs_dat_i(wbs_dat_i),
	.wbs_adr_i({ n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258 }),
	.wbs_ack_o(wbs_ack_o),
	.wbs_dat_o(wbs_dat_o),
	.la_data_in({ n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		la_data_in[65],
		la_data_in[64],
		la_data_in[63],
		la_data_in[62],
		la_data_in[61],
		la_data_in[60],
		la_data_in[59],
		la_data_in[58],
		la_data_in[57],
		la_data_in[56],
		la_data_in[55],
		la_data_in[54],
		la_data_in[53],
		la_data_in[52],
		la_data_in[51],
		la_data_in[50],
		la_data_in[49],
		la_data_in[48],
		la_data_in[47],
		la_data_in[46],
		la_data_in[45],
		la_data_in[44],
		la_data_in[43],
		la_data_in[42],
		la_data_in[41],
		la_data_in[40],
		la_data_in[39],
		la_data_in[38],
		la_data_in[37],
		la_data_in[36],
		la_data_in[35],
		la_data_in[34],
		la_data_in[33],
		la_data_in[32],
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258 }),
	.la_data_out({ SYNOPSYS_UNCONNECTED_1,
		SYNOPSYS_UNCONNECTED_2,
		SYNOPSYS_UNCONNECTED_3,
		SYNOPSYS_UNCONNECTED_4,
		SYNOPSYS_UNCONNECTED_5,
		SYNOPSYS_UNCONNECTED_6,
		SYNOPSYS_UNCONNECTED_7,
		SYNOPSYS_UNCONNECTED_8,
		SYNOPSYS_UNCONNECTED_9,
		SYNOPSYS_UNCONNECTED_10,
		SYNOPSYS_UNCONNECTED_11,
		SYNOPSYS_UNCONNECTED_12,
		SYNOPSYS_UNCONNECTED_13,
		SYNOPSYS_UNCONNECTED_14,
		SYNOPSYS_UNCONNECTED_15,
		SYNOPSYS_UNCONNECTED_16,
		SYNOPSYS_UNCONNECTED_17,
		SYNOPSYS_UNCONNECTED_18,
		SYNOPSYS_UNCONNECTED_19,
		SYNOPSYS_UNCONNECTED_20,
		SYNOPSYS_UNCONNECTED_21,
		SYNOPSYS_UNCONNECTED_22,
		SYNOPSYS_UNCONNECTED_23,
		SYNOPSYS_UNCONNECTED_24,
		SYNOPSYS_UNCONNECTED_25,
		SYNOPSYS_UNCONNECTED_26,
		SYNOPSYS_UNCONNECTED_27,
		SYNOPSYS_UNCONNECTED_28,
		SYNOPSYS_UNCONNECTED_29,
		SYNOPSYS_UNCONNECTED_30,
		SYNOPSYS_UNCONNECTED_31,
		SYNOPSYS_UNCONNECTED_32,
		SYNOPSYS_UNCONNECTED_33,
		SYNOPSYS_UNCONNECTED_34,
		SYNOPSYS_UNCONNECTED_35,
		SYNOPSYS_UNCONNECTED_36,
		SYNOPSYS_UNCONNECTED_37,
		SYNOPSYS_UNCONNECTED_38,
		SYNOPSYS_UNCONNECTED_39,
		SYNOPSYS_UNCONNECTED_40,
		SYNOPSYS_UNCONNECTED_41,
		SYNOPSYS_UNCONNECTED_42,
		SYNOPSYS_UNCONNECTED_43,
		SYNOPSYS_UNCONNECTED_44,
		SYNOPSYS_UNCONNECTED_45,
		SYNOPSYS_UNCONNECTED_46,
		SYNOPSYS_UNCONNECTED_47,
		SYNOPSYS_UNCONNECTED_48,
		SYNOPSYS_UNCONNECTED_49,
		SYNOPSYS_UNCONNECTED_50,
		SYNOPSYS_UNCONNECTED_51,
		SYNOPSYS_UNCONNECTED_52,
		SYNOPSYS_UNCONNECTED_53,
		SYNOPSYS_UNCONNECTED_54,
		SYNOPSYS_UNCONNECTED_55,
		SYNOPSYS_UNCONNECTED_56,
		SYNOPSYS_UNCONNECTED_57,
		SYNOPSYS_UNCONNECTED_58,
		SYNOPSYS_UNCONNECTED_59,
		SYNOPSYS_UNCONNECTED_60,
		SYNOPSYS_UNCONNECTED_61,
		SYNOPSYS_UNCONNECTED_62,
		SYNOPSYS_UNCONNECTED_63,
		SYNOPSYS_UNCONNECTED_64,
		SYNOPSYS_UNCONNECTED_65,
		SYNOPSYS_UNCONNECTED_66,
		SYNOPSYS_UNCONNECTED_67,
		SYNOPSYS_UNCONNECTED_68,
		SYNOPSYS_UNCONNECTED_69,
		SYNOPSYS_UNCONNECTED_70,
		SYNOPSYS_UNCONNECTED_71,
		SYNOPSYS_UNCONNECTED_72,
		SYNOPSYS_UNCONNECTED_73,
		SYNOPSYS_UNCONNECTED_74,
		SYNOPSYS_UNCONNECTED_75,
		SYNOPSYS_UNCONNECTED_76,
		SYNOPSYS_UNCONNECTED_77,
		SYNOPSYS_UNCONNECTED_78,
		SYNOPSYS_UNCONNECTED_79,
		SYNOPSYS_UNCONNECTED_80,
		SYNOPSYS_UNCONNECTED_81,
		SYNOPSYS_UNCONNECTED_82,
		SYNOPSYS_UNCONNECTED_83,
		SYNOPSYS_UNCONNECTED_84,
		SYNOPSYS_UNCONNECTED_85,
		SYNOPSYS_UNCONNECTED_86,
		SYNOPSYS_UNCONNECTED_87,
		SYNOPSYS_UNCONNECTED_88,
		SYNOPSYS_UNCONNECTED_89,
		SYNOPSYS_UNCONNECTED_90,
		SYNOPSYS_UNCONNECTED_91,
		SYNOPSYS_UNCONNECTED_92,
		SYNOPSYS_UNCONNECTED_93,
		SYNOPSYS_UNCONNECTED_94,
		SYNOPSYS_UNCONNECTED_95,
		SYNOPSYS_UNCONNECTED_96,
		la_data_out[31],
		la_data_out[30],
		la_data_out[29],
		la_data_out[28],
		FE_RN_5,
		la_data_out[26],
		FE_OFN14_io_out_25,
		FE_OFN18_io_out_24,
		la_data_out[23],
		la_data_out[22],
		la_data_out[21],
		FE_UNCONNECTEDZ_0,
		FE_UNCONNECTEDZ_1,
		FE_UNCONNECTEDZ_2,
		FE_UNCONNECTEDZ_3,
		FE_UNCONNECTEDZ_4,
		FE_UNCONNECTEDZ_5,
		FE_RN_11,
		FE_RN_12,
		FE_UNCONNECTEDZ_6,
		FE_RN_13,
		FE_UNCONNECTEDZ_7,
		FE_UNCONNECTEDZ_8,
		la_data_out[8],
		la_data_out[7],
		la_data_out[6],
		la_data_out[5],
		la_data_out[4],
		la_data_out[3],
		la_data_out[2],
		FE_RN_14,
		FE_RN_15 }),
	.la_oenb({ n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		la_oenb[65],
		la_oenb[64],
		la_oenb[63],
		la_oenb[62],
		la_oenb[61],
		la_oenb[60],
		la_oenb[59],
		la_oenb[58],
		la_oenb[57],
		la_oenb[56],
		la_oenb[55],
		la_oenb[54],
		la_oenb[53],
		la_oenb[52],
		la_oenb[51],
		la_oenb[50],
		la_oenb[49],
		la_oenb[48],
		la_oenb[47],
		la_oenb[46],
		la_oenb[45],
		la_oenb[44],
		la_oenb[43],
		la_oenb[42],
		la_oenb[41],
		la_oenb[40],
		la_oenb[39],
		la_oenb[38],
		la_oenb[37],
		la_oenb[36],
		la_oenb[35],
		la_oenb[34],
		la_oenb[33],
		la_oenb[32],
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258 }),
	.io_in({ n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258,
		n258 }),
	.io_out({ SYNOPSYS_UNCONNECTED_97,
		SYNOPSYS_UNCONNECTED_98,
		SYNOPSYS_UNCONNECTED_99,
		SYNOPSYS_UNCONNECTED_100,
		SYNOPSYS_UNCONNECTED_101,
		SYNOPSYS_UNCONNECTED_102,
		FE_RN_1,
		FE_RN_2,
		FE_RN_3,
		FE_RN_4,
		io_out[27],
		FE_OFN11_io_out_26,
		FE_UNCONNECTEDZ_9,
		FE_OFN20_io_out_24,
		FE_OFN22_io_out_23,
		FE_OFN25_io_out_22,
		FE_OFN28_io_out_21,
		FE_OFN30_io_out_20,
		FE_RN_6,
		FE_RN_7,
		FE_RN_8,
		FE_RN_9,
		FE_RN_10,
		FE_UNCONNECTEDZ_10,
		FE_UNCONNECTEDZ_11,
		la_data_out[12],
		FE_UNCONNECTEDZ_12,
		la_data_out[10],
		la_data_out[9],
		FE_OFN45_io_out_8,
		FE_OFN48_io_out_7,
		FE_OFN51_io_out_6,
		FE_OFN54_io_out_5,
		FE_OFN57_io_out_4,
		FE_OFN60_io_out_3,
		FE_OFN63_io_out_2,
		io_out[1],
		io_out[0] }),
	.io_oeb({ SYNOPSYS_UNCONNECTED_103,
		FE_RN_16,
		FE_RN_17,
		FE_RN_18,
		FE_RN_19,
		FE_RN_20,
		FE_RN_21,
		FE_UNCONNECTEDZ_13,
		FE_RN_23,
		FE_RN_22,
		FE_RN_24,
		FE_RN_47,
		FE_RN_25,
		FE_RN_48,
		FE_RN_26,
		FE_UNCONNECTEDZ_14,
		FE_RN_27,
		FE_UNCONNECTEDZ_15,
		FE_RN_31,
		FE_RN_46,
		FE_RN_36,
		FE_RN_45,
		FE_RN_35,
		FE_RN_44,
		FE_RN_34,
		FE_RN_43,
		FE_RN_33,
		FE_RN_42,
		FE_RN_32,
		FE_RN_41,
		FE_UNCONNECTEDZ_16,
		FE_RN_40,
		FE_UNCONNECTEDZ_17,
		FE_RN_39,
		FE_RN_29,
		FE_RN_38,
		FE_RN_28,
		FE_RN_37 }),
	.irq({ SYNOPSYS_UNCONNECTED_104,
		SYNOPSYS_UNCONNECTED_105,
		SYNOPSYS_UNCONNECTED_106 }), 
	.vccd1(vccd1), 
	.vssd1(vssd1));
   sky130_fd_sc_hd__conb_1 U259 (
	.HI(n365),
	.LO(n258), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U260 (
	.A(n365),
	.Y(user_irq[0]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U261 (
	.A(n365),
	.Y(user_irq[1]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U262 (
	.A(n365),
	.Y(user_irq[2]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U263 (
	.A(FE_OFN69_n365),
	.Y(io_oeb[37]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U264 (
	.A(FE_OFN69_n365),
	.Y(io_out[32]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U265 (
	.A(FE_OFN69_n365),
	.Y(io_out[33]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U266 (
	.A(FE_OFN69_n365),
	.Y(io_out[34]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U267 (
	.A(FE_OFN69_n365),
	.Y(io_out[35]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U268 (
	.A(FE_OFN69_n365),
	.Y(io_out[36]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U269 (
	.A(FE_OFN69_n365),
	.Y(io_out[37]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U270 (
	.A(FE_OFN69_n365),
	.Y(la_data_out[32]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U271 (
	.A(FE_OFN69_n365),
	.Y(la_data_out[33]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U272 (
	.A(FE_OFN69_n365),
	.Y(la_data_out[34]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U273 (
	.A(FE_OFN69_n365),
	.Y(la_data_out[35]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U274 (
	.A(FE_OFN69_n365),
	.Y(la_data_out[36]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U275 (
	.A(FE_OFN69_n365),
	.Y(la_data_out[37]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U276 (
	.A(FE_OFN69_n365),
	.Y(la_data_out[38]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U277 (
	.A(FE_OFN69_n365),
	.Y(la_data_out[39]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U278 (
	.A(FE_OFN69_n365),
	.Y(la_data_out[40]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U279 (
	.A(FE_OFN69_n365),
	.Y(la_data_out[41]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U280 (
	.A(FE_OFN69_n365),
	.Y(la_data_out[42]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U281 (
	.A(FE_OFN69_n365),
	.Y(la_data_out[43]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U282 (
	.A(FE_OFN69_n365),
	.Y(la_data_out[44]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U283 (
	.A(FE_OFN69_n365),
	.Y(la_data_out[45]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U284 (
	.A(FE_OFN69_n365),
	.Y(la_data_out[46]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U285 (
	.A(FE_OFN69_n365),
	.Y(la_data_out[47]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U286 (
	.A(FE_OFN69_n365),
	.Y(la_data_out[48]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U287 (
	.A(FE_OFN69_n365),
	.Y(la_data_out[49]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U288 (
	.A(FE_OFN69_n365),
	.Y(la_data_out[50]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U289 (
	.A(FE_OFN69_n365),
	.Y(la_data_out[51]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U290 (
	.A(FE_OFN69_n365),
	.Y(la_data_out[52]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U291 (
	.A(FE_OFN69_n365),
	.Y(la_data_out[53]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U292 (
	.A(FE_OFN69_n365),
	.Y(la_data_out[54]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U293 (
	.A(FE_OFN69_n365),
	.Y(la_data_out[55]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U294 (
	.A(FE_OFN69_n365),
	.Y(la_data_out[56]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U295 (
	.A(FE_OFN69_n365),
	.Y(la_data_out[57]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U296 (
	.A(n365),
	.Y(la_data_out[58]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U297 (
	.A(n365),
	.Y(la_data_out[59]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U298 (
	.A(n365),
	.Y(la_data_out[60]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U299 (
	.A(n365),
	.Y(la_data_out[61]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U300 (
	.A(n365),
	.Y(la_data_out[62]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U301 (
	.A(n365),
	.Y(la_data_out[63]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U302 (
	.A(n365),
	.Y(la_data_out[64]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U303 (
	.A(n365),
	.Y(la_data_out[65]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U304 (
	.A(n365),
	.Y(la_data_out[66]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U305 (
	.A(n365),
	.Y(la_data_out[67]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U306 (
	.A(n365),
	.Y(la_data_out[68]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U307 (
	.A(n365),
	.Y(la_data_out[69]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U308 (
	.A(n365),
	.Y(la_data_out[70]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U309 (
	.A(n365),
	.Y(la_data_out[71]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U310 (
	.A(n365),
	.Y(la_data_out[72]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U311 (
	.A(n365),
	.Y(la_data_out[73]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U312 (
	.A(n365),
	.Y(la_data_out[74]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U313 (
	.A(n365),
	.Y(la_data_out[75]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U314 (
	.A(n365),
	.Y(la_data_out[76]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U315 (
	.A(n365),
	.Y(la_data_out[77]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U316 (
	.A(n365),
	.Y(la_data_out[78]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U317 (
	.A(n365),
	.Y(la_data_out[79]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U318 (
	.A(n365),
	.Y(la_data_out[80]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U319 (
	.A(n365),
	.Y(la_data_out[81]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U320 (
	.A(n365),
	.Y(la_data_out[82]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U321 (
	.A(n365),
	.Y(la_data_out[83]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U322 (
	.A(n365),
	.Y(la_data_out[84]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U323 (
	.A(n365),
	.Y(la_data_out[85]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U324 (
	.A(n365),
	.Y(la_data_out[86]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U325 (
	.A(n365),
	.Y(la_data_out[87]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U326 (
	.A(n365),
	.Y(la_data_out[88]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U327 (
	.A(n365),
	.Y(la_data_out[89]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U328 (
	.A(n365),
	.Y(la_data_out[90]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U329 (
	.A(n365),
	.Y(la_data_out[91]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U330 (
	.A(n365),
	.Y(la_data_out[92]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U331 (
	.A(n365),
	.Y(la_data_out[93]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U332 (
	.A(n365),
	.Y(la_data_out[94]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U333 (
	.A(n365),
	.Y(la_data_out[95]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U334 (
	.A(n365),
	.Y(la_data_out[96]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U335 (
	.A(n365),
	.Y(la_data_out[97]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U336 (
	.A(n365),
	.Y(la_data_out[98]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U337 (
	.A(n365),
	.Y(la_data_out[99]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U338 (
	.A(n365),
	.Y(la_data_out[100]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U339 (
	.A(n365),
	.Y(la_data_out[101]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U340 (
	.A(n365),
	.Y(la_data_out[102]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U341 (
	.A(n365),
	.Y(la_data_out[103]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U342 (
	.A(n365),
	.Y(la_data_out[104]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U343 (
	.A(n365),
	.Y(la_data_out[105]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U344 (
	.A(n365),
	.Y(la_data_out[106]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U345 (
	.A(n365),
	.Y(la_data_out[107]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U346 (
	.A(n365),
	.Y(la_data_out[108]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U347 (
	.A(n365),
	.Y(la_data_out[109]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U348 (
	.A(n365),
	.Y(la_data_out[110]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U349 (
	.A(n365),
	.Y(la_data_out[111]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U350 (
	.A(n365),
	.Y(la_data_out[112]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U351 (
	.A(n365),
	.Y(la_data_out[113]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U352 (
	.A(n365),
	.Y(la_data_out[114]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U353 (
	.A(n365),
	.Y(la_data_out[115]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U354 (
	.A(n365),
	.Y(la_data_out[116]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U355 (
	.A(n365),
	.Y(la_data_out[117]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U356 (
	.A(n365),
	.Y(la_data_out[118]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U357 (
	.A(n365),
	.Y(la_data_out[119]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U358 (
	.A(n365),
	.Y(la_data_out[120]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U359 (
	.A(n365),
	.Y(la_data_out[121]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U360 (
	.A(n365),
	.Y(la_data_out[122]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U361 (
	.A(n365),
	.Y(la_data_out[123]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U362 (
	.A(n365),
	.Y(la_data_out[124]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U363 (
	.A(n365),
	.Y(la_data_out[125]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U364 (
	.A(n365),
	.Y(la_data_out[126]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
   sky130_fd_sc_hd__clkinvlp_2 U365 (
	.A(n365),
	.Y(la_data_out[127]), 
	.VPWR(vccd1), 
	.VPB(vccd1), 
	.VNB(vssd1), 
	.VGND(vssd1));
endmodule

